<?php

declare(strict_types=1);

namespace Telnyx\MessagingHostedNumberOrders\MessagingHostedNumberOrderCheckEligibilityResponse\PhoneNumber;

/**
 * The eligibility status of the phone number.
 */
enum EligibleStatus: string
{
    case NUMBER_CAN_NOT_BE_REPEATED = 'NUMBER_CAN_NOT_BE_REPEATED';

    case NUMBER_CAN_NOT_BE_VALIDATED = 'NUMBER_CAN_NOT_BE_VALIDATED';

    case NUMBER_CAN_NOT_BE_WIRELESS = 'NUMBER_CAN_NOT_BE_WIRELESS';

    case NUMBER_CAN_NOT_BE_ACTIVE_IN_YOUR_ACCOUNT = 'NUMBER_CAN_NOT_BE_ACTIVE_IN_YOUR_ACCOUNT';

    case NUMBER_CAN_NOT_HOSTED_WITH_A_TELNYX_SUBSCRIBER = 'NUMBER_CAN_NOT_HOSTED_WITH_A_TELNYX_SUBSCRIBER';

    case NUMBER_CAN_NOT_BE_IN_TELNYX = 'NUMBER_CAN_NOT_BE_IN_TELNYX';

    case NUMBER_IS_NOT_A_US_NUMBER = 'NUMBER_IS_NOT_A_US_NUMBER';

    case NUMBER_IS_NOT_A_VALID_ROUTING_NUMBER = 'NUMBER_IS_NOT_A_VALID_ROUTING_NUMBER';

    case NUMBER_IS_NOT_IN_E164_FORMAT = 'NUMBER_IS_NOT_IN_E164_FORMAT';

    case BILLING_ACCOUNT_CHECK_FAILED = 'BILLING_ACCOUNT_CHECK_FAILED';

    case BILLING_ACCOUNT_IS_ABOLISHED = 'BILLING_ACCOUNT_IS_ABOLISHED';

    case ELIGIBLE = 'ELIGIBLE';
}
