<?php

declare(strict_types=1);

namespace Telnyx\Services\Messaging10dlc;

use Telnyx\Client;
use Telnyx\Core\Exceptions\APIException;
use Telnyx\Core\Util;
use Telnyx\Messaging10dlc\Campaign\TelnyxCampaignCsp;
use Telnyx\RequestOptions;
use Telnyx\ServiceContracts\Messaging10dlc\CampaignBuilderContract;
use Telnyx\Services\Messaging10dlc\CampaignBuilder\BrandService;

final class CampaignBuilderService implements CampaignBuilderContract
{
    /**
     * @api
     */
    public CampaignBuilderRawService $raw;

    /**
     * @api
     */
    public BrandService $brand;

    /**
     * @internal
     */
    public function __construct(private Client $client)
    {
        $this->raw = new CampaignBuilderRawService($client);
        $this->brand = new BrandService($client);
    }

    /**
     * @api
     *
     * Before creating a campaign, use the [Qualify By Usecase endpoint](https://developers.telnyx.com/api/messaging/10dlc/get-usecase-qualification) to ensure that the brand you want to assign a new campaign to is qualified for the desired use case of that campaign. **Please note:** After campaign creation, you'll only be able to edit the campaign's sample messages. Creating a campaign will entail an upfront, non-refundable three month's cost that will depend on the campaign's use case ([see 10DLC Costs section for details](https://developers.telnyx.com/docs/messaging/10dlc/concepts#10dlc-costs)).
     *
     * @param string $brandID alphanumeric identifier of the brand associated with this campaign
     * @param string $description summary description of this campaign
     * @param string $usecase Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase` operation to retrieve usecases available for given brand.
     * @param bool $ageGated age gated message content in campaign
     * @param bool $autoRenewal Campaign subscription auto-renewal option. If set to true, then campaign will automatically renewal at end of billing cycle.
     * @param bool $directLending Direct lending or loan arrangement
     * @param bool $embeddedLink Does message generated by the campaign include URL link in SMS?
     * @param string $embeddedLinkSample sample of an embedded link that will be sent to subscribers
     * @param bool $embeddedPhone Does message generated by the campaign include phone number in SMS?
     * @param string $helpKeywords Subscriber help keywords. Multiple keywords are comma separated without space.
     * @param string $helpMessage help message of the campaign
     * @param string $messageFlow message flow description
     * @param list<int> $mnoIDs Submit campaign to given list of MNOs by MNO's network ID. Default is all MNOs if no value provided.
     * @param bool $numberPool Does campaign utilize pool of phone numbers?
     * @param string $optinKeywords Subscriber opt-in keywords. Multiple keywords are comma separated without space.
     * @param string $optinMessage subscriber opt-in message
     * @param string $optoutKeywords Subscriber opt-out keywords. Multiple keywords are comma separated without space.
     * @param string $optoutMessage subscriber opt-out message
     * @param string $privacyPolicyLink link to the campaign's privacy policy
     * @param string $referenceID Caller supplied campaign reference ID. If supplied, the value must be unique across all submitted campaigns. Can be used to prevent duplicate campaign registrations.
     * @param string $resellerID alphanumeric identifier of the reseller that you want to associate with this campaign
     * @param string $sample1 Message sample. Some campaign tiers require 1 or more message samples.
     * @param string $sample2 Message sample. Some campaign tiers require 2 or more message samples.
     * @param string $sample3 Message sample. Some campaign tiers require 3 or more message samples.
     * @param string $sample4 Message sample. Some campaign tiers require 4 or more message samples.
     * @param string $sample5 Message sample. Some campaign tiers require 5 or more message samples.
     * @param bool $subscriberHelp Does campaign responds to help keyword(s)?
     * @param bool $subscriberOptin Does campaign require subscriber to opt-in before SMS is sent to subscriber?
     * @param bool $subscriberOptout Does campaign support subscriber opt-out keyword(s)?
     * @param list<string> $subUsecases Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/registry/enum/usecase` operation to retrieve list of valid sub-usecases
     * @param list<string> $tag tags to be set on the Campaign
     * @param bool $termsAndConditions Is terms and conditions accepted?
     * @param string $termsAndConditionsLink link to the campaign's terms and conditions
     * @param string $webhookFailoverURL failover webhook to which campaign status updates are sent
     * @param string $webhookURL webhook to which campaign status updates are sent
     *
     * @throws APIException
     */
    public function submit(
        string $brandID,
        string $description,
        string $usecase,
        ?bool $ageGated = null,
        ?bool $autoRenewal = null,
        ?bool $directLending = null,
        ?bool $embeddedLink = null,
        ?string $embeddedLinkSample = null,
        ?bool $embeddedPhone = null,
        ?string $helpKeywords = null,
        ?string $helpMessage = null,
        ?string $messageFlow = null,
        ?array $mnoIDs = null,
        ?bool $numberPool = null,
        ?string $optinKeywords = null,
        ?string $optinMessage = null,
        ?string $optoutKeywords = null,
        ?string $optoutMessage = null,
        ?string $privacyPolicyLink = null,
        ?string $referenceID = null,
        ?string $resellerID = null,
        ?string $sample1 = null,
        ?string $sample2 = null,
        ?string $sample3 = null,
        ?string $sample4 = null,
        ?string $sample5 = null,
        ?bool $subscriberHelp = null,
        ?bool $subscriberOptin = null,
        ?bool $subscriberOptout = null,
        ?array $subUsecases = null,
        ?array $tag = null,
        ?bool $termsAndConditions = null,
        ?string $termsAndConditionsLink = null,
        ?string $webhookFailoverURL = null,
        ?string $webhookURL = null,
        ?RequestOptions $requestOptions = null,
    ): TelnyxCampaignCsp {
        $params = Util::removeNulls(
            [
                'brandID' => $brandID,
                'description' => $description,
                'usecase' => $usecase,
                'ageGated' => $ageGated,
                'autoRenewal' => $autoRenewal,
                'directLending' => $directLending,
                'embeddedLink' => $embeddedLink,
                'embeddedLinkSample' => $embeddedLinkSample,
                'embeddedPhone' => $embeddedPhone,
                'helpKeywords' => $helpKeywords,
                'helpMessage' => $helpMessage,
                'messageFlow' => $messageFlow,
                'mnoIDs' => $mnoIDs,
                'numberPool' => $numberPool,
                'optinKeywords' => $optinKeywords,
                'optinMessage' => $optinMessage,
                'optoutKeywords' => $optoutKeywords,
                'optoutMessage' => $optoutMessage,
                'privacyPolicyLink' => $privacyPolicyLink,
                'referenceID' => $referenceID,
                'resellerID' => $resellerID,
                'sample1' => $sample1,
                'sample2' => $sample2,
                'sample3' => $sample3,
                'sample4' => $sample4,
                'sample5' => $sample5,
                'subscriberHelp' => $subscriberHelp,
                'subscriberOptin' => $subscriberOptin,
                'subscriberOptout' => $subscriberOptout,
                'subUsecases' => $subUsecases,
                'tag' => $tag,
                'termsAndConditions' => $termsAndConditions,
                'termsAndConditionsLink' => $termsAndConditionsLink,
                'webhookFailoverURL' => $webhookFailoverURL,
                'webhookURL' => $webhookURL,
            ],
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->submit(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }
}
