configured_endpoints: 946
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/telnyx%2Ftelnyx-f5d32dda757d3d3b1ff14fe2fdfa8bf601c4cc2b5db801b91d4dc789aa471109.yml
openapi_spec_hash: b9ca26b16d63a5d521dfbeea420678b7
config_hash: baebbcd781bd25a3bf4a023a730ab6c3
