<?php

declare(strict_types=1);

namespace Telnyx\Messaging10dlc\CampaignBuilder;

use Telnyx\Core\Attributes\Optional;
use Telnyx\Core\Attributes\Required;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Concerns\SdkParams;
use Telnyx\Core\Contracts\BaseModel;

/**
 * Before creating a campaign, use the [Qualify By Usecase endpoint](https://developers.telnyx.com/api/messaging/10dlc/get-usecase-qualification) to ensure that the brand you want to assign a new campaign to is qualified for the desired use case of that campaign. **Please note:** After campaign creation, you'll only be able to edit the campaign's sample messages. Creating a campaign will entail an upfront, non-refundable three month's cost that will depend on the campaign's use case ([see 10DLC Costs section for details](https://developers.telnyx.com/docs/messaging/10dlc/concepts#10dlc-costs)).
 *
 * @see Telnyx\Services\Messaging10dlc\CampaignBuilderService::submit()
 *
 * @phpstan-type CampaignBuilderSubmitParamsShape = array{
 *   brandID: string,
 *   description: string,
 *   usecase: string,
 *   ageGated?: bool|null,
 *   autoRenewal?: bool|null,
 *   directLending?: bool|null,
 *   embeddedLink?: bool|null,
 *   embeddedLinkSample?: string|null,
 *   embeddedPhone?: bool|null,
 *   helpKeywords?: string|null,
 *   helpMessage?: string|null,
 *   messageFlow?: string|null,
 *   mnoIDs?: list<int>|null,
 *   numberPool?: bool|null,
 *   optinKeywords?: string|null,
 *   optinMessage?: string|null,
 *   optoutKeywords?: string|null,
 *   optoutMessage?: string|null,
 *   privacyPolicyLink?: string|null,
 *   referenceID?: string|null,
 *   resellerID?: string|null,
 *   sample1?: string|null,
 *   sample2?: string|null,
 *   sample3?: string|null,
 *   sample4?: string|null,
 *   sample5?: string|null,
 *   subscriberHelp?: bool|null,
 *   subscriberOptin?: bool|null,
 *   subscriberOptout?: bool|null,
 *   subUsecases?: list<string>|null,
 *   tag?: list<string>|null,
 *   termsAndConditions?: bool|null,
 *   termsAndConditionsLink?: string|null,
 *   webhookFailoverURL?: string|null,
 *   webhookURL?: string|null,
 * }
 */
final class CampaignBuilderSubmitParams implements BaseModel
{
    /** @use SdkModel<CampaignBuilderSubmitParamsShape> */
    use SdkModel;
    use SdkParams;

    /**
     * Alphanumeric identifier of the brand associated with this campaign.
     */
    #[Required('brandId')]
    public string $brandID;

    /**
     * Summary description of this campaign.
     */
    #[Required]
    public string $description;

    /**
     * Campaign usecase. Must be of defined valid types. Use `/10dlc/enum/usecase` operation to retrieve usecases available for given brand.
     */
    #[Required]
    public string $usecase;

    /**
     * Age gated message content in campaign.
     */
    #[Optional]
    public ?bool $ageGated;

    /**
     * Campaign subscription auto-renewal option. If set to true, then campaign will automatically renewal at end of billing cycle.
     */
    #[Optional]
    public ?bool $autoRenewal;

    /**
     * Direct lending or loan arrangement.
     */
    #[Optional]
    public ?bool $directLending;

    /**
     * Does message generated by the campaign include URL link in SMS?
     */
    #[Optional]
    public ?bool $embeddedLink;

    /**
     * Sample of an embedded link that will be sent to subscribers.
     */
    #[Optional]
    public ?string $embeddedLinkSample;

    /**
     * Does message generated by the campaign include phone number in SMS?
     */
    #[Optional]
    public ?bool $embeddedPhone;

    /**
     * Subscriber help keywords. Multiple keywords are comma separated without space.
     */
    #[Optional]
    public ?string $helpKeywords;

    /**
     * Help message of the campaign.
     */
    #[Optional]
    public ?string $helpMessage;

    /**
     * Message flow description.
     */
    #[Optional]
    public ?string $messageFlow;

    /**
     * Submit campaign to given list of MNOs by MNO's network ID. Default is all MNOs if no value provided.
     *
     * @var list<int>|null $mnoIDs
     */
    #[Optional('mnoIds', list: 'int')]
    public ?array $mnoIDs;

    /**
     * Does campaign utilize pool of phone numbers?
     */
    #[Optional]
    public ?bool $numberPool;

    /**
     * Subscriber opt-in keywords. Multiple keywords are comma separated without space.
     */
    #[Optional]
    public ?string $optinKeywords;

    /**
     * Subscriber opt-in message.
     */
    #[Optional]
    public ?string $optinMessage;

    /**
     * Subscriber opt-out keywords. Multiple keywords are comma separated without space.
     */
    #[Optional]
    public ?string $optoutKeywords;

    /**
     * Subscriber opt-out message.
     */
    #[Optional]
    public ?string $optoutMessage;

    /**
     * Link to the campaign's privacy policy.
     */
    #[Optional]
    public ?string $privacyPolicyLink;

    /**
     * Caller supplied campaign reference ID. If supplied, the value must be unique across all submitted campaigns. Can be used to prevent duplicate campaign registrations.
     */
    #[Optional('referenceId')]
    public ?string $referenceID;

    /**
     * Alphanumeric identifier of the reseller that you want to associate with this campaign.
     */
    #[Optional('resellerId')]
    public ?string $resellerID;

    /**
     * Message sample. Some campaign tiers require 1 or more message samples.
     */
    #[Optional]
    public ?string $sample1;

    /**
     * Message sample. Some campaign tiers require 2 or more message samples.
     */
    #[Optional]
    public ?string $sample2;

    /**
     * Message sample. Some campaign tiers require 3 or more message samples.
     */
    #[Optional]
    public ?string $sample3;

    /**
     * Message sample. Some campaign tiers require 4 or more message samples.
     */
    #[Optional]
    public ?string $sample4;

    /**
     * Message sample. Some campaign tiers require 5 or more message samples.
     */
    #[Optional]
    public ?string $sample5;

    /**
     * Does campaign responds to help keyword(s)?
     */
    #[Optional]
    public ?bool $subscriberHelp;

    /**
     * Does campaign require subscriber to opt-in before SMS is sent to subscriber?
     */
    #[Optional]
    public ?bool $subscriberOptin;

    /**
     * Does campaign support subscriber opt-out keyword(s)?
     */
    #[Optional]
    public ?bool $subscriberOptout;

    /**
     * Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/10dlc/enum/usecase` operation to retrieve list of valid sub-usecases.
     *
     * @var list<string>|null $subUsecases
     */
    #[Optional(list: 'string')]
    public ?array $subUsecases;

    /**
     * Tags to be set on the Campaign.
     *
     * @var list<string>|null $tag
     */
    #[Optional(list: 'string')]
    public ?array $tag;

    /**
     * Is terms and conditions accepted?
     */
    #[Optional]
    public ?bool $termsAndConditions;

    /**
     * Link to the campaign's terms and conditions.
     */
    #[Optional]
    public ?string $termsAndConditionsLink;

    /**
     * Failover webhook to which campaign status updates are sent.
     */
    #[Optional]
    public ?string $webhookFailoverURL;

    /**
     * Webhook to which campaign status updates are sent.
     */
    #[Optional]
    public ?string $webhookURL;

    /**
     * `new CampaignBuilderSubmitParams()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * CampaignBuilderSubmitParams::with(brandID: ..., description: ..., usecase: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new CampaignBuilderSubmitParams)
     *   ->withBrandID(...)
     *   ->withDescription(...)
     *   ->withUsecase(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<int>|null $mnoIDs
     * @param list<string>|null $subUsecases
     * @param list<string>|null $tag
     */
    public static function with(
        string $brandID,
        string $description,
        string $usecase,
        ?bool $ageGated = null,
        ?bool $autoRenewal = null,
        ?bool $directLending = null,
        ?bool $embeddedLink = null,
        ?string $embeddedLinkSample = null,
        ?bool $embeddedPhone = null,
        ?string $helpKeywords = null,
        ?string $helpMessage = null,
        ?string $messageFlow = null,
        ?array $mnoIDs = null,
        ?bool $numberPool = null,
        ?string $optinKeywords = null,
        ?string $optinMessage = null,
        ?string $optoutKeywords = null,
        ?string $optoutMessage = null,
        ?string $privacyPolicyLink = null,
        ?string $referenceID = null,
        ?string $resellerID = null,
        ?string $sample1 = null,
        ?string $sample2 = null,
        ?string $sample3 = null,
        ?string $sample4 = null,
        ?string $sample5 = null,
        ?bool $subscriberHelp = null,
        ?bool $subscriberOptin = null,
        ?bool $subscriberOptout = null,
        ?array $subUsecases = null,
        ?array $tag = null,
        ?bool $termsAndConditions = null,
        ?string $termsAndConditionsLink = null,
        ?string $webhookFailoverURL = null,
        ?string $webhookURL = null,
    ): self {
        $self = new self;

        $self['brandID'] = $brandID;
        $self['description'] = $description;
        $self['usecase'] = $usecase;

        null !== $ageGated && $self['ageGated'] = $ageGated;
        null !== $autoRenewal && $self['autoRenewal'] = $autoRenewal;
        null !== $directLending && $self['directLending'] = $directLending;
        null !== $embeddedLink && $self['embeddedLink'] = $embeddedLink;
        null !== $embeddedLinkSample && $self['embeddedLinkSample'] = $embeddedLinkSample;
        null !== $embeddedPhone && $self['embeddedPhone'] = $embeddedPhone;
        null !== $helpKeywords && $self['helpKeywords'] = $helpKeywords;
        null !== $helpMessage && $self['helpMessage'] = $helpMessage;
        null !== $messageFlow && $self['messageFlow'] = $messageFlow;
        null !== $mnoIDs && $self['mnoIDs'] = $mnoIDs;
        null !== $numberPool && $self['numberPool'] = $numberPool;
        null !== $optinKeywords && $self['optinKeywords'] = $optinKeywords;
        null !== $optinMessage && $self['optinMessage'] = $optinMessage;
        null !== $optoutKeywords && $self['optoutKeywords'] = $optoutKeywords;
        null !== $optoutMessage && $self['optoutMessage'] = $optoutMessage;
        null !== $privacyPolicyLink && $self['privacyPolicyLink'] = $privacyPolicyLink;
        null !== $referenceID && $self['referenceID'] = $referenceID;
        null !== $resellerID && $self['resellerID'] = $resellerID;
        null !== $sample1 && $self['sample1'] = $sample1;
        null !== $sample2 && $self['sample2'] = $sample2;
        null !== $sample3 && $self['sample3'] = $sample3;
        null !== $sample4 && $self['sample4'] = $sample4;
        null !== $sample5 && $self['sample5'] = $sample5;
        null !== $subscriberHelp && $self['subscriberHelp'] = $subscriberHelp;
        null !== $subscriberOptin && $self['subscriberOptin'] = $subscriberOptin;
        null !== $subscriberOptout && $self['subscriberOptout'] = $subscriberOptout;
        null !== $subUsecases && $self['subUsecases'] = $subUsecases;
        null !== $tag && $self['tag'] = $tag;
        null !== $termsAndConditions && $self['termsAndConditions'] = $termsAndConditions;
        null !== $termsAndConditionsLink && $self['termsAndConditionsLink'] = $termsAndConditionsLink;
        null !== $webhookFailoverURL && $self['webhookFailoverURL'] = $webhookFailoverURL;
        null !== $webhookURL && $self['webhookURL'] = $webhookURL;

        return $self;
    }

    /**
     * Alphanumeric identifier of the brand associated with this campaign.
     */
    public function withBrandID(string $brandID): self
    {
        $self = clone $this;
        $self['brandID'] = $brandID;

        return $self;
    }

    /**
     * Summary description of this campaign.
     */
    public function withDescription(string $description): self
    {
        $self = clone $this;
        $self['description'] = $description;

        return $self;
    }

    /**
     * Campaign usecase. Must be of defined valid types. Use `/10dlc/enum/usecase` operation to retrieve usecases available for given brand.
     */
    public function withUsecase(string $usecase): self
    {
        $self = clone $this;
        $self['usecase'] = $usecase;

        return $self;
    }

    /**
     * Age gated message content in campaign.
     */
    public function withAgeGated(bool $ageGated): self
    {
        $self = clone $this;
        $self['ageGated'] = $ageGated;

        return $self;
    }

    /**
     * Campaign subscription auto-renewal option. If set to true, then campaign will automatically renewal at end of billing cycle.
     */
    public function withAutoRenewal(bool $autoRenewal): self
    {
        $self = clone $this;
        $self['autoRenewal'] = $autoRenewal;

        return $self;
    }

    /**
     * Direct lending or loan arrangement.
     */
    public function withDirectLending(bool $directLending): self
    {
        $self = clone $this;
        $self['directLending'] = $directLending;

        return $self;
    }

    /**
     * Does message generated by the campaign include URL link in SMS?
     */
    public function withEmbeddedLink(bool $embeddedLink): self
    {
        $self = clone $this;
        $self['embeddedLink'] = $embeddedLink;

        return $self;
    }

    /**
     * Sample of an embedded link that will be sent to subscribers.
     */
    public function withEmbeddedLinkSample(string $embeddedLinkSample): self
    {
        $self = clone $this;
        $self['embeddedLinkSample'] = $embeddedLinkSample;

        return $self;
    }

    /**
     * Does message generated by the campaign include phone number in SMS?
     */
    public function withEmbeddedPhone(bool $embeddedPhone): self
    {
        $self = clone $this;
        $self['embeddedPhone'] = $embeddedPhone;

        return $self;
    }

    /**
     * Subscriber help keywords. Multiple keywords are comma separated without space.
     */
    public function withHelpKeywords(string $helpKeywords): self
    {
        $self = clone $this;
        $self['helpKeywords'] = $helpKeywords;

        return $self;
    }

    /**
     * Help message of the campaign.
     */
    public function withHelpMessage(string $helpMessage): self
    {
        $self = clone $this;
        $self['helpMessage'] = $helpMessage;

        return $self;
    }

    /**
     * Message flow description.
     */
    public function withMessageFlow(string $messageFlow): self
    {
        $self = clone $this;
        $self['messageFlow'] = $messageFlow;

        return $self;
    }

    /**
     * Submit campaign to given list of MNOs by MNO's network ID. Default is all MNOs if no value provided.
     *
     * @param list<int> $mnoIDs
     */
    public function withMnoIDs(array $mnoIDs): self
    {
        $self = clone $this;
        $self['mnoIDs'] = $mnoIDs;

        return $self;
    }

    /**
     * Does campaign utilize pool of phone numbers?
     */
    public function withNumberPool(bool $numberPool): self
    {
        $self = clone $this;
        $self['numberPool'] = $numberPool;

        return $self;
    }

    /**
     * Subscriber opt-in keywords. Multiple keywords are comma separated without space.
     */
    public function withOptinKeywords(string $optinKeywords): self
    {
        $self = clone $this;
        $self['optinKeywords'] = $optinKeywords;

        return $self;
    }

    /**
     * Subscriber opt-in message.
     */
    public function withOptinMessage(string $optinMessage): self
    {
        $self = clone $this;
        $self['optinMessage'] = $optinMessage;

        return $self;
    }

    /**
     * Subscriber opt-out keywords. Multiple keywords are comma separated without space.
     */
    public function withOptoutKeywords(string $optoutKeywords): self
    {
        $self = clone $this;
        $self['optoutKeywords'] = $optoutKeywords;

        return $self;
    }

    /**
     * Subscriber opt-out message.
     */
    public function withOptoutMessage(string $optoutMessage): self
    {
        $self = clone $this;
        $self['optoutMessage'] = $optoutMessage;

        return $self;
    }

    /**
     * Link to the campaign's privacy policy.
     */
    public function withPrivacyPolicyLink(string $privacyPolicyLink): self
    {
        $self = clone $this;
        $self['privacyPolicyLink'] = $privacyPolicyLink;

        return $self;
    }

    /**
     * Caller supplied campaign reference ID. If supplied, the value must be unique across all submitted campaigns. Can be used to prevent duplicate campaign registrations.
     */
    public function withReferenceID(string $referenceID): self
    {
        $self = clone $this;
        $self['referenceID'] = $referenceID;

        return $self;
    }

    /**
     * Alphanumeric identifier of the reseller that you want to associate with this campaign.
     */
    public function withResellerID(string $resellerID): self
    {
        $self = clone $this;
        $self['resellerID'] = $resellerID;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 1 or more message samples.
     */
    public function withSample1(string $sample1): self
    {
        $self = clone $this;
        $self['sample1'] = $sample1;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 2 or more message samples.
     */
    public function withSample2(string $sample2): self
    {
        $self = clone $this;
        $self['sample2'] = $sample2;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 3 or more message samples.
     */
    public function withSample3(string $sample3): self
    {
        $self = clone $this;
        $self['sample3'] = $sample3;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 4 or more message samples.
     */
    public function withSample4(string $sample4): self
    {
        $self = clone $this;
        $self['sample4'] = $sample4;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 5 or more message samples.
     */
    public function withSample5(string $sample5): self
    {
        $self = clone $this;
        $self['sample5'] = $sample5;

        return $self;
    }

    /**
     * Does campaign responds to help keyword(s)?
     */
    public function withSubscriberHelp(bool $subscriberHelp): self
    {
        $self = clone $this;
        $self['subscriberHelp'] = $subscriberHelp;

        return $self;
    }

    /**
     * Does campaign require subscriber to opt-in before SMS is sent to subscriber?
     */
    public function withSubscriberOptin(bool $subscriberOptin): self
    {
        $self = clone $this;
        $self['subscriberOptin'] = $subscriberOptin;

        return $self;
    }

    /**
     * Does campaign support subscriber opt-out keyword(s)?
     */
    public function withSubscriberOptout(bool $subscriberOptout): self
    {
        $self = clone $this;
        $self['subscriberOptout'] = $subscriberOptout;

        return $self;
    }

    /**
     * Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/10dlc/enum/usecase` operation to retrieve list of valid sub-usecases.
     *
     * @param list<string> $subUsecases
     */
    public function withSubUsecases(array $subUsecases): self
    {
        $self = clone $this;
        $self['subUsecases'] = $subUsecases;

        return $self;
    }

    /**
     * Tags to be set on the Campaign.
     *
     * @param list<string> $tag
     */
    public function withTag(array $tag): self
    {
        $self = clone $this;
        $self['tag'] = $tag;

        return $self;
    }

    /**
     * Is terms and conditions accepted?
     */
    public function withTermsAndConditions(bool $termsAndConditions): self
    {
        $self = clone $this;
        $self['termsAndConditions'] = $termsAndConditions;

        return $self;
    }

    /**
     * Link to the campaign's terms and conditions.
     */
    public function withTermsAndConditionsLink(
        string $termsAndConditionsLink
    ): self {
        $self = clone $this;
        $self['termsAndConditionsLink'] = $termsAndConditionsLink;

        return $self;
    }

    /**
     * Failover webhook to which campaign status updates are sent.
     */
    public function withWebhookFailoverURL(string $webhookFailoverURL): self
    {
        $self = clone $this;
        $self['webhookFailoverURL'] = $webhookFailoverURL;

        return $self;
    }

    /**
     * Webhook to which campaign status updates are sent.
     */
    public function withWebhookURL(string $webhookURL): self
    {
        $self = clone $this;
        $self['webhookURL'] = $webhookURL;

        return $self;
    }
}
