<?php

declare(strict_types=1);

namespace Telnyx\Services;

use Telnyx\Client;
use Telnyx\Core\Exceptions\APIException;
use Telnyx\Core\Util;
use Telnyx\DefaultFlatPagination;
use Telnyx\MessagingProfiles\MessagingProfile;
use Telnyx\MessagingProfiles\MessagingProfileCreateParams\WebhookAPIVersion;
use Telnyx\MessagingProfiles\MessagingProfileDeleteResponse;
use Telnyx\MessagingProfiles\MessagingProfileGetMetricsResponse;
use Telnyx\MessagingProfiles\MessagingProfileGetResponse;
use Telnyx\MessagingProfiles\MessagingProfileListAlphanumericSenderIDsResponse;
use Telnyx\MessagingProfiles\MessagingProfileListParams\Filter;
use Telnyx\MessagingProfiles\MessagingProfileNewResponse;
use Telnyx\MessagingProfiles\MessagingProfileRetrieveMetricsParams\TimeFrame;
use Telnyx\MessagingProfiles\MessagingProfileUpdateResponse;
use Telnyx\MessagingProfiles\NumberPoolSettings;
use Telnyx\MessagingProfiles\URLShortenerSettings;
use Telnyx\PhoneNumberWithMessagingSettings;
use Telnyx\RequestOptions;
use Telnyx\ServiceContracts\MessagingProfilesContract;
use Telnyx\Services\MessagingProfiles\ActionsService;
use Telnyx\Services\MessagingProfiles\AutorespConfigsService;
use Telnyx\ShortCode;

/**
 * @phpstan-import-type FilterShape from \Telnyx\MessagingProfiles\MessagingProfileListParams\Filter
 * @phpstan-import-type NumberPoolSettingsShape from \Telnyx\MessagingProfiles\NumberPoolSettings
 * @phpstan-import-type URLShortenerSettingsShape from \Telnyx\MessagingProfiles\URLShortenerSettings
 * @phpstan-import-type RequestOpts from \Telnyx\RequestOptions
 */
final class MessagingProfilesService implements MessagingProfilesContract
{
    /**
     * @api
     */
    public MessagingProfilesRawService $raw;

    /**
     * @api
     */
    public AutorespConfigsService $autorespConfigs;

    /**
     * @api
     */
    public ActionsService $actions;

    /**
     * @internal
     */
    public function __construct(private Client $client)
    {
        $this->raw = new MessagingProfilesRawService($client);
        $this->autorespConfigs = new AutorespConfigsService($client);
        $this->actions = new ActionsService($client);
    }

    /**
     * @api
     *
     * Create a messaging profile
     *
     * @param string $name a user friendly name for the messaging profile
     * @param list<string> $whitelistedDestinations Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]` all destinations will be allowed.
     * @param string|null $aiAssistantID the AI assistant ID to associate with this messaging profile
     * @param string|null $alphaSender the alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID
     * @param string $dailySpendLimit the maximum amount of money (in USD) that can be spent by this profile before midnight UTC
     * @param bool $dailySpendLimitEnabled whether to enforce the value configured by `daily_spend_limit`
     * @param bool $enabled specifies whether the messaging profile is enabled or not
     * @param string|null $healthWebhookURL a URL to receive health check webhooks for numbers in this profile
     * @param bool $mmsFallBackToSMS enables SMS fallback for MMS messages
     * @param bool $mmsTranscoding enables automated resizing of MMS media
     * @param bool $mobileOnly send messages only to mobile phone numbers
     * @param NumberPoolSettings|NumberPoolSettingsShape|null $numberPoolSettings Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     * @param string|null $resourceGroupID the resource group ID to associate with this messaging profile
     * @param bool $smartEncoding Enables automatic character encoding optimization for SMS messages. When enabled, the system automatically selects the most efficient encoding (GSM-7 or UCS-2) based on message content to maximize character limits and minimize costs.
     * @param URLShortenerSettings|URLShortenerSettingsShape|null $urlShortenerSettings The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion> $webhookAPIVersion determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format
     * @param string|null $webhookFailoverURL the failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails
     * @param string|null $webhookURL the URL where webhooks related to this messaging profile will be sent
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function create(
        string $name,
        array $whitelistedDestinations,
        ?string $aiAssistantID = null,
        ?string $alphaSender = null,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        bool $enabled = true,
        ?string $healthWebhookURL = null,
        bool $mmsFallBackToSMS = false,
        bool $mmsTranscoding = false,
        bool $mobileOnly = false,
        NumberPoolSettings|array|null $numberPoolSettings = null,
        ?string $resourceGroupID = null,
        bool $smartEncoding = false,
        URLShortenerSettings|array|null $urlShortenerSettings = null,
        WebhookAPIVersion|string $webhookAPIVersion = '2',
        ?string $webhookFailoverURL = '',
        ?string $webhookURL = '',
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileNewResponse {
        $params = Util::removeNulls(
            [
                'name' => $name,
                'whitelistedDestinations' => $whitelistedDestinations,
                'aiAssistantID' => $aiAssistantID,
                'alphaSender' => $alphaSender,
                'dailySpendLimit' => $dailySpendLimit,
                'dailySpendLimitEnabled' => $dailySpendLimitEnabled,
                'enabled' => $enabled,
                'healthWebhookURL' => $healthWebhookURL,
                'mmsFallBackToSMS' => $mmsFallBackToSMS,
                'mmsTranscoding' => $mmsTranscoding,
                'mobileOnly' => $mobileOnly,
                'numberPoolSettings' => $numberPoolSettings,
                'resourceGroupID' => $resourceGroupID,
                'smartEncoding' => $smartEncoding,
                'urlShortenerSettings' => $urlShortenerSettings,
                'webhookAPIVersion' => $webhookAPIVersion,
                'webhookFailoverURL' => $webhookFailoverURL,
                'webhookURL' => $webhookURL,
            ],
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->create(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Retrieve a messaging profile
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function retrieve(
        string $messagingProfileID,
        RequestOptions|array|null $requestOptions = null
    ): MessagingProfileGetResponse {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->retrieve($messagingProfileID, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Update a messaging profile
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param string|null $alphaSender the alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID
     * @param string $dailySpendLimit the maximum amount of money (in USD) that can be spent by this profile before midnight UTC
     * @param bool $dailySpendLimitEnabled whether to enforce the value configured by `daily_spend_limit`
     * @param bool $enabled specifies whether the messaging profile is enabled or not
     * @param bool $mmsFallBackToSMS enables SMS fallback for MMS messages
     * @param bool $mmsTranscoding enables automated resizing of MMS media
     * @param bool $mobileOnly send messages only to mobile phone numbers
     * @param string $name a user friendly name for the messaging profile
     * @param NumberPoolSettings|NumberPoolSettingsShape|null $numberPoolSettings Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     * @param bool $smartEncoding Enables automatic character encoding optimization for SMS messages. When enabled, the system automatically selects the most efficient encoding (GSM-7 or UCS-2) based on message content to maximize character limits and minimize costs.
     * @param URLShortenerSettings|URLShortenerSettingsShape|null $urlShortenerSettings The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     * @param string $v1Secret secret used to authenticate with v1 endpoints
     * @param \Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion|value-of<\Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion> $webhookAPIVersion determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format
     * @param string|null $webhookFailoverURL the failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails
     * @param string|null $webhookURL the URL where webhooks related to this messaging profile will be sent
     * @param list<string> $whitelistedDestinations Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]`, all destinations will be allowed.
     *
     * This field is required if the messaging profile doesn't have it defined yet.
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function update(
        string $messagingProfileID,
        ?string $alphaSender = null,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        ?bool $enabled = null,
        bool $mmsFallBackToSMS = false,
        bool $mmsTranscoding = false,
        bool $mobileOnly = false,
        ?string $name = null,
        NumberPoolSettings|array|null $numberPoolSettings = null,
        bool $smartEncoding = false,
        URLShortenerSettings|array|null $urlShortenerSettings = null,
        ?string $v1Secret = null,
        \Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion|string|null $webhookAPIVersion = null,
        ?string $webhookFailoverURL = null,
        ?string $webhookURL = null,
        ?array $whitelistedDestinations = null,
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileUpdateResponse {
        $params = Util::removeNulls(
            [
                'alphaSender' => $alphaSender,
                'dailySpendLimit' => $dailySpendLimit,
                'dailySpendLimitEnabled' => $dailySpendLimitEnabled,
                'enabled' => $enabled,
                'mmsFallBackToSMS' => $mmsFallBackToSMS,
                'mmsTranscoding' => $mmsTranscoding,
                'mobileOnly' => $mobileOnly,
                'name' => $name,
                'numberPoolSettings' => $numberPoolSettings,
                'smartEncoding' => $smartEncoding,
                'urlShortenerSettings' => $urlShortenerSettings,
                'v1Secret' => $v1Secret,
                'webhookAPIVersion' => $webhookAPIVersion,
                'webhookFailoverURL' => $webhookFailoverURL,
                'webhookURL' => $webhookURL,
                'whitelistedDestinations' => $whitelistedDestinations,
            ],
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->update($messagingProfileID, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * List messaging profiles
     *
     * @param Filter|FilterShape $filter Consolidated filter parameter (deepObject style). Originally: filter[name]
     * @param string $filterNameContains filter profiles by name containing the given string
     * @param string $filterNameEq filter profiles by exact name match
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultFlatPagination<MessagingProfile>
     *
     * @throws APIException
     */
    public function list(
        Filter|array|null $filter = null,
        ?string $filterNameContains = null,
        ?string $filterNameEq = null,
        ?int $pageNumber = null,
        ?int $pageSize = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultFlatPagination {
        $params = Util::removeNulls(
            [
                'filter' => $filter,
                'filterNameContains' => $filterNameContains,
                'filterNameEq' => $filterNameEq,
                'pageNumber' => $pageNumber,
                'pageSize' => $pageSize,
            ],
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->list(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Delete a messaging profile
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function delete(
        string $messagingProfileID,
        RequestOptions|array|null $requestOptions = null
    ): MessagingProfileDeleteResponse {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->delete($messagingProfileID, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * List all alphanumeric sender IDs associated with a specific messaging profile.
     *
     * @param string $id the identifier of the messaging profile
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultFlatPagination<MessagingProfileListAlphanumericSenderIDsResponse>
     *
     * @throws APIException
     */
    public function listAlphanumericSenderIDs(
        string $id,
        int $pageNumber = 1,
        int $pageSize = 20,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultFlatPagination {
        $params = Util::removeNulls(
            ['pageNumber' => $pageNumber, 'pageSize' => $pageSize]
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->listAlphanumericSenderIDs($id, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * List phone numbers associated with a messaging profile
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultFlatPagination<PhoneNumberWithMessagingSettings>
     *
     * @throws APIException
     */
    public function listPhoneNumbers(
        string $messagingProfileID,
        ?int $pageNumber = null,
        ?int $pageSize = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultFlatPagination {
        $params = Util::removeNulls(
            ['pageNumber' => $pageNumber, 'pageSize' => $pageSize]
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->listPhoneNumbers($messagingProfileID, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * List short codes associated with a messaging profile
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultFlatPagination<ShortCode>
     *
     * @throws APIException
     */
    public function listShortCodes(
        string $messagingProfileID,
        ?int $pageNumber = null,
        ?int $pageSize = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultFlatPagination {
        $params = Util::removeNulls(
            ['pageNumber' => $pageNumber, 'pageSize' => $pageSize]
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->listShortCodes($messagingProfileID, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Get detailed metrics for a specific messaging profile, broken down by time interval.
     *
     * @param string $id the identifier of the messaging profile
     * @param TimeFrame|value-of<TimeFrame> $timeFrame the time frame for metrics
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function retrieveMetrics(
        string $id,
        TimeFrame|string $timeFrame = '24h',
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileGetMetricsResponse {
        $params = Util::removeNulls(['timeFrame' => $timeFrame]);

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->retrieveMetrics($id, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }
}
