<?php

declare(strict_types=1);

namespace Telnyx\Services;

use Telnyx\Client;
use Telnyx\Core\Exceptions\APIException;
use Telnyx\MessagingProfiles\MessagingProfileCreateParams\WebhookAPIVersion;
use Telnyx\MessagingProfiles\MessagingProfileDeleteResponse;
use Telnyx\MessagingProfiles\MessagingProfileGetResponse;
use Telnyx\MessagingProfiles\MessagingProfileListPhoneNumbersResponse;
use Telnyx\MessagingProfiles\MessagingProfileListResponse;
use Telnyx\MessagingProfiles\MessagingProfileListShortCodesResponse;
use Telnyx\MessagingProfiles\MessagingProfileNewResponse;
use Telnyx\MessagingProfiles\MessagingProfileUpdateResponse;
use Telnyx\MessagingProfiles\NumberPoolSettings;
use Telnyx\MessagingProfiles\URLShortenerSettings;
use Telnyx\RequestOptions;
use Telnyx\ServiceContracts\MessagingProfilesContract;
use Telnyx\Services\MessagingProfiles\AutorespConfigsService;

final class MessagingProfilesService implements MessagingProfilesContract
{
    /**
     * @api
     */
    public MessagingProfilesRawService $raw;

    /**
     * @api
     */
    public AutorespConfigsService $autorespConfigs;

    /**
     * @internal
     */
    public function __construct(private Client $client)
    {
        $this->raw = new MessagingProfilesRawService($client);
        $this->autorespConfigs = new AutorespConfigsService($client);
    }

    /**
     * @api
     *
     * Create a messaging profile
     *
     * @param string $name a user friendly name for the messaging profile
     * @param list<string> $whitelistedDestinations Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]` all destinations will be allowed.
     * @param string|null $alphaSender the alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID
     * @param string $dailySpendLimit the maximum amount of money (in USD) that can be spent by this profile before midnight UTC
     * @param bool $dailySpendLimitEnabled whether to enforce the value configured by `daily_spend_limit`
     * @param bool $enabled specifies whether the messaging profile is enabled or not
     * @param bool $mmsFallBackToSMS enables SMS fallback for MMS messages
     * @param bool $mmsTranscoding enables automated resizing of MMS media
     * @param bool $mobileOnly send messages only to mobile phone numbers
     * @param array{
     *   longCodeWeight: float,
     *   skipUnhealthy: bool,
     *   tollFreeWeight: float,
     *   geomatch?: bool,
     *   stickySender?: bool,
     * }|NumberPoolSettings|null $numberPoolSettings Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     * @param array{
     *   domain: string,
     *   prefix?: string,
     *   replaceBlacklistOnly?: bool,
     *   sendWebhooks?: bool,
     * }|URLShortenerSettings|null $urlShortenerSettings The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     * @param '1'|'2'|'2010-04-01'|WebhookAPIVersion $webhookAPIVersion determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format
     * @param string|null $webhookFailoverURL the failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails
     * @param string|null $webhookURL the URL where webhooks related to this messaging profile will be sent
     *
     * @throws APIException
     */
    public function create(
        string $name,
        array $whitelistedDestinations,
        ?string $alphaSender = null,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        bool $enabled = true,
        bool $mmsFallBackToSMS = false,
        bool $mmsTranscoding = false,
        bool $mobileOnly = false,
        array|NumberPoolSettings|null $numberPoolSettings = null,
        array|URLShortenerSettings|null $urlShortenerSettings = null,
        string|WebhookAPIVersion $webhookAPIVersion = '2',
        ?string $webhookFailoverURL = '',
        ?string $webhookURL = '',
        ?RequestOptions $requestOptions = null,
    ): MessagingProfileNewResponse {
        $params = [
            'name' => $name,
            'whitelistedDestinations' => $whitelistedDestinations,
            'alphaSender' => $alphaSender,
            'dailySpendLimit' => $dailySpendLimit,
            'dailySpendLimitEnabled' => $dailySpendLimitEnabled,
            'enabled' => $enabled,
            'mmsFallBackToSMS' => $mmsFallBackToSMS,
            'mmsTranscoding' => $mmsTranscoding,
            'mobileOnly' => $mobileOnly,
            'numberPoolSettings' => $numberPoolSettings,
            'urlShortenerSettings' => $urlShortenerSettings,
            'webhookAPIVersion' => $webhookAPIVersion,
            'webhookFailoverURL' => $webhookFailoverURL,
            'webhookURL' => $webhookURL,
        ];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->create(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Retrieve a messaging profile
     *
     * @param string $id The id of the messaging profile to retrieve
     *
     * @throws APIException
     */
    public function retrieve(
        string $id,
        ?RequestOptions $requestOptions = null
    ): MessagingProfileGetResponse {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->retrieve($id, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Update a messaging profile
     *
     * @param string $id The id of the messaging profile to retrieve
     * @param string|null $alphaSender the alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID
     * @param string $dailySpendLimit the maximum amount of money (in USD) that can be spent by this profile before midnight UTC
     * @param bool $dailySpendLimitEnabled whether to enforce the value configured by `daily_spend_limit`
     * @param bool $enabled specifies whether the messaging profile is enabled or not
     * @param bool $mmsFallBackToSMS enables SMS fallback for MMS messages
     * @param bool $mmsTranscoding enables automated resizing of MMS media
     * @param bool $mobileOnly send messages only to mobile phone numbers
     * @param string $name a user friendly name for the messaging profile
     * @param array{
     *   longCodeWeight: float,
     *   skipUnhealthy: bool,
     *   tollFreeWeight: float,
     *   geomatch?: bool,
     *   stickySender?: bool,
     * }|NumberPoolSettings|null $numberPoolSettings Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     * @param array{
     *   domain: string,
     *   prefix?: string,
     *   replaceBlacklistOnly?: bool,
     *   sendWebhooks?: bool,
     * }|URLShortenerSettings|null $urlShortenerSettings The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     * @param string $v1Secret secret used to authenticate with v1 endpoints
     * @param '1'|'2'|'2010-04-01'|\Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion $webhookAPIVersion determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format
     * @param string|null $webhookFailoverURL the failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails
     * @param string|null $webhookURL the URL where webhooks related to this messaging profile will be sent
     * @param list<string> $whitelistedDestinations Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]`, all destinations will be allowed.
     *
     * This field is required if the messaging profile doesn't have it defined yet.
     *
     * @throws APIException
     */
    public function update(
        string $id,
        ?string $alphaSender = null,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        ?bool $enabled = null,
        bool $mmsFallBackToSMS = false,
        bool $mmsTranscoding = false,
        bool $mobileOnly = false,
        ?string $name = null,
        array|NumberPoolSettings|null $numberPoolSettings = null,
        array|URLShortenerSettings|null $urlShortenerSettings = null,
        ?string $v1Secret = null,
        string|\Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion|null $webhookAPIVersion = null,
        ?string $webhookFailoverURL = null,
        ?string $webhookURL = null,
        ?array $whitelistedDestinations = null,
        ?RequestOptions $requestOptions = null,
    ): MessagingProfileUpdateResponse {
        $params = [
            'alphaSender' => $alphaSender,
            'dailySpendLimit' => $dailySpendLimit,
            'dailySpendLimitEnabled' => $dailySpendLimitEnabled,
            'enabled' => $enabled,
            'mmsFallBackToSMS' => $mmsFallBackToSMS,
            'mmsTranscoding' => $mmsTranscoding,
            'mobileOnly' => $mobileOnly,
            'name' => $name,
            'numberPoolSettings' => $numberPoolSettings,
            'urlShortenerSettings' => $urlShortenerSettings,
            'v1Secret' => $v1Secret,
            'webhookAPIVersion' => $webhookAPIVersion,
            'webhookFailoverURL' => $webhookFailoverURL,
            'webhookURL' => $webhookURL,
            'whitelistedDestinations' => $whitelistedDestinations,
        ];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->update($id, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * List messaging profiles
     *
     * @param array{
     *   name?: string
     * } $filter Consolidated filter parameter (deepObject style). Originally: filter[name]
     * @param array{
     *   number?: int, size?: int
     * } $page Consolidated page parameter (deepObject style). Originally: page[number], page[size]
     *
     * @throws APIException
     */
    public function list(
        ?array $filter = null,
        ?array $page = null,
        ?RequestOptions $requestOptions = null,
    ): MessagingProfileListResponse {
        $params = ['filter' => $filter, 'page' => $page];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->list(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Delete a messaging profile
     *
     * @param string $id The id of the messaging profile to retrieve
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        ?RequestOptions $requestOptions = null
    ): MessagingProfileDeleteResponse {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->delete($id, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * List phone numbers associated with a messaging profile
     *
     * @param string $id The id of the messaging profile to retrieve
     * @param array{
     *   number?: int, size?: int
     * } $page Consolidated page parameter (deepObject style). Originally: page[number], page[size]
     *
     * @throws APIException
     */
    public function listPhoneNumbers(
        string $id,
        ?array $page = null,
        ?RequestOptions $requestOptions = null
    ): MessagingProfileListPhoneNumbersResponse {
        $params = ['page' => $page];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->listPhoneNumbers($id, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * List short codes associated with a messaging profile
     *
     * @param string $id The id of the messaging profile to retrieve
     * @param array{
     *   number?: int, size?: int
     * } $page Consolidated page parameter (deepObject style). Originally: page[number], page[size]
     *
     * @throws APIException
     */
    public function listShortCodes(
        string $id,
        ?array $page = null,
        ?RequestOptions $requestOptions = null
    ): MessagingProfileListShortCodesResponse {
        $params = ['page' => $page];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->listShortCodes($id, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }
}
