<?php

declare(strict_types=1);

namespace Telnyx\Messaging10dlc\Campaign;

use Telnyx\Core\Attributes\Optional;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Contracts\BaseModel;
use Telnyx\Messaging10dlc\Campaign\CampaignListResponse\CampaignStatus;
use Telnyx\Messaging10dlc\Campaign\CampaignListResponse\SubmissionStatus;

/**
 * @phpstan-type CampaignListResponseShape = array{
 *   ageGated?: bool|null,
 *   assignedPhoneNumbersCount?: float|null,
 *   autoRenewal?: bool|null,
 *   billedDate?: string|null,
 *   brandDisplayName?: string|null,
 *   brandID?: string|null,
 *   campaignID?: string|null,
 *   campaignStatus?: value-of<CampaignStatus>|null,
 *   createDate?: string|null,
 *   cspID?: string|null,
 *   description?: string|null,
 *   directLending?: bool|null,
 *   embeddedLink?: bool|null,
 *   embeddedLinkSample?: string|null,
 *   embeddedPhone?: bool|null,
 *   failureReasons?: string|null,
 *   helpKeywords?: string|null,
 *   helpMessage?: string|null,
 *   isTMobileNumberPoolingEnabled?: bool|null,
 *   isTMobileRegistered?: bool|null,
 *   isTMobileSuspended?: bool|null,
 *   messageFlow?: string|null,
 *   mock?: bool|null,
 *   nextRenewalOrExpirationDate?: string|null,
 *   numberPool?: bool|null,
 *   optinKeywords?: string|null,
 *   optinMessage?: string|null,
 *   optoutKeywords?: string|null,
 *   optoutMessage?: string|null,
 *   privacyPolicyLink?: string|null,
 *   referenceID?: string|null,
 *   resellerID?: string|null,
 *   sample1?: string|null,
 *   sample2?: string|null,
 *   sample3?: string|null,
 *   sample4?: string|null,
 *   sample5?: string|null,
 *   status?: string|null,
 *   submissionStatus?: value-of<SubmissionStatus>|null,
 *   subscriberHelp?: bool|null,
 *   subscriberOptin?: bool|null,
 *   subscriberOptout?: bool|null,
 *   subUsecases?: list<string>|null,
 *   tcrBrandID?: string|null,
 *   tcrCampaignID?: string|null,
 *   termsAndConditions?: bool|null,
 *   termsAndConditionsLink?: string|null,
 *   usecase?: string|null,
 *   vertical?: string|null,
 *   webhookFailoverURL?: string|null,
 *   webhookURL?: string|null,
 * }
 */
final class CampaignListResponse implements BaseModel
{
    /** @use SdkModel<CampaignListResponseShape> */
    use SdkModel;

    /**
     * Age gated content in campaign.
     */
    #[Optional]
    public ?bool $ageGated;

    /**
     * Number of phone numbers associated with the campaign.
     */
    #[Optional]
    public ?float $assignedPhoneNumbersCount;

    /**
     * Campaign subscription auto-renewal status.
     */
    #[Optional]
    public ?bool $autoRenewal;

    /**
     * Campaign recent billed date.
     */
    #[Optional]
    public ?string $billedDate;

    /**
     * Display or marketing name of the brand.
     */
    #[Optional]
    public ?string $brandDisplayName;

    /**
     * Unique identifier assigned to the brand.
     */
    #[Optional('brandId')]
    public ?string $brandID;

    /**
     * Unique identifier for a campaign.
     */
    #[Optional('campaignId')]
    public ?string $campaignID;

    /**
     * Campaign status.
     *
     * @var value-of<CampaignStatus>|null $campaignStatus
     */
    #[Optional(enum: CampaignStatus::class)]
    public ?string $campaignStatus;

    /**
     * Unix timestamp when campaign was created.
     */
    #[Optional]
    public ?string $createDate;

    /**
     * Alphanumeric identifier of the CSP associated with this campaign.
     */
    #[Optional('cspId')]
    public ?string $cspID;

    /**
     * Summary description of this campaign.
     */
    #[Optional]
    public ?string $description;

    #[Optional]
    public ?bool $directLending;

    /**
     * Does message generated by the campaign include URL link in SMS?
     */
    #[Optional]
    public ?bool $embeddedLink;

    /**
     * Sample of an embedded link that will be sent to subscribers.
     */
    #[Optional]
    public ?string $embeddedLinkSample;

    /**
     * Does message generated by the campaign include phone number in SMS?
     */
    #[Optional]
    public ?bool $embeddedPhone;

    /**
     * Failure reasons if campaign submission failed.
     */
    #[Optional]
    public ?string $failureReasons;

    /**
     * Subscriber help keywords. Multiple keywords are comma separated without space.
     */
    #[Optional]
    public ?string $helpKeywords;

    /**
     * Help message of the campaign.
     */
    #[Optional]
    public ?string $helpMessage;

    /**
     * Indicates whether the campaign has a T-Mobile number pool ID associated with it.
     */
    #[Optional]
    public ?bool $isTMobileNumberPoolingEnabled;

    /**
     * Indicates whether the campaign is registered with T-Mobile.
     */
    #[Optional]
    public ?bool $isTMobileRegistered;

    /**
     * Indicates whether the campaign is suspended with T-Mobile.
     */
    #[Optional]
    public ?bool $isTMobileSuspended;

    /**
     * Message flow description.
     */
    #[Optional]
    public ?string $messageFlow;

    /**
     * Campaign created from mock brand. Mocked campaign cannot be shared with an upstream CNP.
     */
    #[Optional]
    public ?bool $mock;

    /**
     * When the campaign would be due for its next renew/bill date.
     */
    #[Optional]
    public ?string $nextRenewalOrExpirationDate;

    /**
     * Does campaign utilize pool of phone numbers?
     */
    #[Optional]
    public ?bool $numberPool;

    /**
     * Subscriber opt-in keywords. Multiple keywords are comma separated without space.
     */
    #[Optional]
    public ?string $optinKeywords;

    /**
     * Subscriber opt-in message.
     */
    #[Optional]
    public ?string $optinMessage;

    /**
     * Subscriber opt-out keywords. Multiple keywords are comma separated without space.
     */
    #[Optional]
    public ?string $optoutKeywords;

    /**
     * Subscriber opt-out message.
     */
    #[Optional]
    public ?string $optoutMessage;

    /**
     * Link to the campaign's privacy policy.
     */
    #[Optional]
    public ?string $privacyPolicyLink;

    /**
     * Caller supplied campaign reference ID. If supplied, the value must be unique across all submitted campaigns. Can be used to prevent duplicate campaign registrations.
     */
    #[Optional('referenceId')]
    public ?string $referenceID;

    /**
     * Alphanumeric identifier of the reseller that you want to associate with this campaign.
     */
    #[Optional('resellerId')]
    public ?string $resellerID;

    /**
     * Message sample. Some campaign tiers require 1 or more message samples.
     */
    #[Optional]
    public ?string $sample1;

    /**
     * Message sample. Some campaign tiers require 2 or more message samples.
     */
    #[Optional]
    public ?string $sample2;

    /**
     * Message sample. Some campaign tiers require 3 or more message samples.
     */
    #[Optional]
    public ?string $sample3;

    /**
     * Message sample. Some campaign tiers require 4 or more message samples.
     */
    #[Optional]
    public ?string $sample4;

    /**
     * Message sample. Some campaign tiers require 5 or more message samples.
     */
    #[Optional]
    public ?string $sample5;

    /**
     * Current campaign status. Possible values: ACTIVE, EXPIRED. A newly created campaign defaults to ACTIVE status.
     */
    #[Optional]
    public ?string $status;

    /**
     * Campaign submission status.
     *
     * @var value-of<SubmissionStatus>|null $submissionStatus
     */
    #[Optional(enum: SubmissionStatus::class)]
    public ?string $submissionStatus;

    /**
     * Does campaign responds to help keyword(s)?
     */
    #[Optional]
    public ?bool $subscriberHelp;

    /**
     * Does campaign require subscriber to opt-in before SMS is sent to subscriber?
     */
    #[Optional]
    public ?bool $subscriberOptin;

    /**
     * Does campaign support subscriber opt-out keyword(s)?
     */
    #[Optional]
    public ?bool $subscriberOptout;

    /**
     * Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/registry/enum/usecase` operation to retrieve list of valid sub-usecases.
     *
     * @var list<string>|null $subUsecases
     */
    #[Optional(list: 'string')]
    public ?array $subUsecases;

    /**
     * Unique identifier assigned to the brand by the registry.
     */
    #[Optional('tcrBrandId')]
    public ?string $tcrBrandID;

    /**
     * Unique identifier assigned to the campaign by the registry.
     */
    #[Optional('tcrCampaignId')]
    public ?string $tcrCampaignID;

    /**
     * Is terms & conditions accepted?
     */
    #[Optional]
    public ?bool $termsAndConditions;

    /**
     * Link to the campaign's terms and conditions.
     */
    #[Optional]
    public ?string $termsAndConditionsLink;

    /**
     * Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase` operation to retrieve usecases available for given brand.
     */
    #[Optional]
    public ?string $usecase;

    /**
     * @deprecated This field is deprecated and will be removed soon
     *
     * Business/industry segment of this campaign (Deprecated). Must be of defined valid types. Use `/registry/enum/vertical` operation to retrieve verticals available for given brand, vertical combination.
     *
     * This field is deprecated.
     */
    #[Optional]
    public ?string $vertical;

    /**
     * Failover webhook to which campaign status updates are sent.
     */
    #[Optional]
    public ?string $webhookFailoverURL;

    /**
     * Webhook to which campaign status updates are sent.
     */
    #[Optional]
    public ?string $webhookURL;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param CampaignStatus|value-of<CampaignStatus> $campaignStatus
     * @param SubmissionStatus|value-of<SubmissionStatus> $submissionStatus
     * @param list<string> $subUsecases
     */
    public static function with(
        ?bool $ageGated = null,
        ?float $assignedPhoneNumbersCount = null,
        ?bool $autoRenewal = null,
        ?string $billedDate = null,
        ?string $brandDisplayName = null,
        ?string $brandID = null,
        ?string $campaignID = null,
        CampaignStatus|string|null $campaignStatus = null,
        ?string $createDate = null,
        ?string $cspID = null,
        ?string $description = null,
        ?bool $directLending = null,
        ?bool $embeddedLink = null,
        ?string $embeddedLinkSample = null,
        ?bool $embeddedPhone = null,
        ?string $failureReasons = null,
        ?string $helpKeywords = null,
        ?string $helpMessage = null,
        ?bool $isTMobileNumberPoolingEnabled = null,
        ?bool $isTMobileRegistered = null,
        ?bool $isTMobileSuspended = null,
        ?string $messageFlow = null,
        ?bool $mock = null,
        ?string $nextRenewalOrExpirationDate = null,
        ?bool $numberPool = null,
        ?string $optinKeywords = null,
        ?string $optinMessage = null,
        ?string $optoutKeywords = null,
        ?string $optoutMessage = null,
        ?string $privacyPolicyLink = null,
        ?string $referenceID = null,
        ?string $resellerID = null,
        ?string $sample1 = null,
        ?string $sample2 = null,
        ?string $sample3 = null,
        ?string $sample4 = null,
        ?string $sample5 = null,
        ?string $status = null,
        SubmissionStatus|string|null $submissionStatus = null,
        ?bool $subscriberHelp = null,
        ?bool $subscriberOptin = null,
        ?bool $subscriberOptout = null,
        ?array $subUsecases = null,
        ?string $tcrBrandID = null,
        ?string $tcrCampaignID = null,
        ?bool $termsAndConditions = null,
        ?string $termsAndConditionsLink = null,
        ?string $usecase = null,
        ?string $vertical = null,
        ?string $webhookFailoverURL = null,
        ?string $webhookURL = null,
    ): self {
        $self = new self;

        null !== $ageGated && $self['ageGated'] = $ageGated;
        null !== $assignedPhoneNumbersCount && $self['assignedPhoneNumbersCount'] = $assignedPhoneNumbersCount;
        null !== $autoRenewal && $self['autoRenewal'] = $autoRenewal;
        null !== $billedDate && $self['billedDate'] = $billedDate;
        null !== $brandDisplayName && $self['brandDisplayName'] = $brandDisplayName;
        null !== $brandID && $self['brandID'] = $brandID;
        null !== $campaignID && $self['campaignID'] = $campaignID;
        null !== $campaignStatus && $self['campaignStatus'] = $campaignStatus;
        null !== $createDate && $self['createDate'] = $createDate;
        null !== $cspID && $self['cspID'] = $cspID;
        null !== $description && $self['description'] = $description;
        null !== $directLending && $self['directLending'] = $directLending;
        null !== $embeddedLink && $self['embeddedLink'] = $embeddedLink;
        null !== $embeddedLinkSample && $self['embeddedLinkSample'] = $embeddedLinkSample;
        null !== $embeddedPhone && $self['embeddedPhone'] = $embeddedPhone;
        null !== $failureReasons && $self['failureReasons'] = $failureReasons;
        null !== $helpKeywords && $self['helpKeywords'] = $helpKeywords;
        null !== $helpMessage && $self['helpMessage'] = $helpMessage;
        null !== $isTMobileNumberPoolingEnabled && $self['isTMobileNumberPoolingEnabled'] = $isTMobileNumberPoolingEnabled;
        null !== $isTMobileRegistered && $self['isTMobileRegistered'] = $isTMobileRegistered;
        null !== $isTMobileSuspended && $self['isTMobileSuspended'] = $isTMobileSuspended;
        null !== $messageFlow && $self['messageFlow'] = $messageFlow;
        null !== $mock && $self['mock'] = $mock;
        null !== $nextRenewalOrExpirationDate && $self['nextRenewalOrExpirationDate'] = $nextRenewalOrExpirationDate;
        null !== $numberPool && $self['numberPool'] = $numberPool;
        null !== $optinKeywords && $self['optinKeywords'] = $optinKeywords;
        null !== $optinMessage && $self['optinMessage'] = $optinMessage;
        null !== $optoutKeywords && $self['optoutKeywords'] = $optoutKeywords;
        null !== $optoutMessage && $self['optoutMessage'] = $optoutMessage;
        null !== $privacyPolicyLink && $self['privacyPolicyLink'] = $privacyPolicyLink;
        null !== $referenceID && $self['referenceID'] = $referenceID;
        null !== $resellerID && $self['resellerID'] = $resellerID;
        null !== $sample1 && $self['sample1'] = $sample1;
        null !== $sample2 && $self['sample2'] = $sample2;
        null !== $sample3 && $self['sample3'] = $sample3;
        null !== $sample4 && $self['sample4'] = $sample4;
        null !== $sample5 && $self['sample5'] = $sample5;
        null !== $status && $self['status'] = $status;
        null !== $submissionStatus && $self['submissionStatus'] = $submissionStatus;
        null !== $subscriberHelp && $self['subscriberHelp'] = $subscriberHelp;
        null !== $subscriberOptin && $self['subscriberOptin'] = $subscriberOptin;
        null !== $subscriberOptout && $self['subscriberOptout'] = $subscriberOptout;
        null !== $subUsecases && $self['subUsecases'] = $subUsecases;
        null !== $tcrBrandID && $self['tcrBrandID'] = $tcrBrandID;
        null !== $tcrCampaignID && $self['tcrCampaignID'] = $tcrCampaignID;
        null !== $termsAndConditions && $self['termsAndConditions'] = $termsAndConditions;
        null !== $termsAndConditionsLink && $self['termsAndConditionsLink'] = $termsAndConditionsLink;
        null !== $usecase && $self['usecase'] = $usecase;
        null !== $vertical && $self['vertical'] = $vertical;
        null !== $webhookFailoverURL && $self['webhookFailoverURL'] = $webhookFailoverURL;
        null !== $webhookURL && $self['webhookURL'] = $webhookURL;

        return $self;
    }

    /**
     * Age gated content in campaign.
     */
    public function withAgeGated(bool $ageGated): self
    {
        $self = clone $this;
        $self['ageGated'] = $ageGated;

        return $self;
    }

    /**
     * Number of phone numbers associated with the campaign.
     */
    public function withAssignedPhoneNumbersCount(
        float $assignedPhoneNumbersCount
    ): self {
        $self = clone $this;
        $self['assignedPhoneNumbersCount'] = $assignedPhoneNumbersCount;

        return $self;
    }

    /**
     * Campaign subscription auto-renewal status.
     */
    public function withAutoRenewal(bool $autoRenewal): self
    {
        $self = clone $this;
        $self['autoRenewal'] = $autoRenewal;

        return $self;
    }

    /**
     * Campaign recent billed date.
     */
    public function withBilledDate(string $billedDate): self
    {
        $self = clone $this;
        $self['billedDate'] = $billedDate;

        return $self;
    }

    /**
     * Display or marketing name of the brand.
     */
    public function withBrandDisplayName(string $brandDisplayName): self
    {
        $self = clone $this;
        $self['brandDisplayName'] = $brandDisplayName;

        return $self;
    }

    /**
     * Unique identifier assigned to the brand.
     */
    public function withBrandID(string $brandID): self
    {
        $self = clone $this;
        $self['brandID'] = $brandID;

        return $self;
    }

    /**
     * Unique identifier for a campaign.
     */
    public function withCampaignID(string $campaignID): self
    {
        $self = clone $this;
        $self['campaignID'] = $campaignID;

        return $self;
    }

    /**
     * Campaign status.
     *
     * @param CampaignStatus|value-of<CampaignStatus> $campaignStatus
     */
    public function withCampaignStatus(
        CampaignStatus|string $campaignStatus
    ): self {
        $self = clone $this;
        $self['campaignStatus'] = $campaignStatus;

        return $self;
    }

    /**
     * Unix timestamp when campaign was created.
     */
    public function withCreateDate(string $createDate): self
    {
        $self = clone $this;
        $self['createDate'] = $createDate;

        return $self;
    }

    /**
     * Alphanumeric identifier of the CSP associated with this campaign.
     */
    public function withCspID(string $cspID): self
    {
        $self = clone $this;
        $self['cspID'] = $cspID;

        return $self;
    }

    /**
     * Summary description of this campaign.
     */
    public function withDescription(string $description): self
    {
        $self = clone $this;
        $self['description'] = $description;

        return $self;
    }

    public function withDirectLending(bool $directLending): self
    {
        $self = clone $this;
        $self['directLending'] = $directLending;

        return $self;
    }

    /**
     * Does message generated by the campaign include URL link in SMS?
     */
    public function withEmbeddedLink(bool $embeddedLink): self
    {
        $self = clone $this;
        $self['embeddedLink'] = $embeddedLink;

        return $self;
    }

    /**
     * Sample of an embedded link that will be sent to subscribers.
     */
    public function withEmbeddedLinkSample(string $embeddedLinkSample): self
    {
        $self = clone $this;
        $self['embeddedLinkSample'] = $embeddedLinkSample;

        return $self;
    }

    /**
     * Does message generated by the campaign include phone number in SMS?
     */
    public function withEmbeddedPhone(bool $embeddedPhone): self
    {
        $self = clone $this;
        $self['embeddedPhone'] = $embeddedPhone;

        return $self;
    }

    /**
     * Failure reasons if campaign submission failed.
     */
    public function withFailureReasons(string $failureReasons): self
    {
        $self = clone $this;
        $self['failureReasons'] = $failureReasons;

        return $self;
    }

    /**
     * Subscriber help keywords. Multiple keywords are comma separated without space.
     */
    public function withHelpKeywords(string $helpKeywords): self
    {
        $self = clone $this;
        $self['helpKeywords'] = $helpKeywords;

        return $self;
    }

    /**
     * Help message of the campaign.
     */
    public function withHelpMessage(string $helpMessage): self
    {
        $self = clone $this;
        $self['helpMessage'] = $helpMessage;

        return $self;
    }

    /**
     * Indicates whether the campaign has a T-Mobile number pool ID associated with it.
     */
    public function withIsTMobileNumberPoolingEnabled(
        bool $isTMobileNumberPoolingEnabled
    ): self {
        $self = clone $this;
        $self['isTMobileNumberPoolingEnabled'] = $isTMobileNumberPoolingEnabled;

        return $self;
    }

    /**
     * Indicates whether the campaign is registered with T-Mobile.
     */
    public function withIsTMobileRegistered(bool $isTMobileRegistered): self
    {
        $self = clone $this;
        $self['isTMobileRegistered'] = $isTMobileRegistered;

        return $self;
    }

    /**
     * Indicates whether the campaign is suspended with T-Mobile.
     */
    public function withIsTMobileSuspended(bool $isTMobileSuspended): self
    {
        $self = clone $this;
        $self['isTMobileSuspended'] = $isTMobileSuspended;

        return $self;
    }

    /**
     * Message flow description.
     */
    public function withMessageFlow(string $messageFlow): self
    {
        $self = clone $this;
        $self['messageFlow'] = $messageFlow;

        return $self;
    }

    /**
     * Campaign created from mock brand. Mocked campaign cannot be shared with an upstream CNP.
     */
    public function withMock(bool $mock): self
    {
        $self = clone $this;
        $self['mock'] = $mock;

        return $self;
    }

    /**
     * When the campaign would be due for its next renew/bill date.
     */
    public function withNextRenewalOrExpirationDate(
        string $nextRenewalOrExpirationDate
    ): self {
        $self = clone $this;
        $self['nextRenewalOrExpirationDate'] = $nextRenewalOrExpirationDate;

        return $self;
    }

    /**
     * Does campaign utilize pool of phone numbers?
     */
    public function withNumberPool(bool $numberPool): self
    {
        $self = clone $this;
        $self['numberPool'] = $numberPool;

        return $self;
    }

    /**
     * Subscriber opt-in keywords. Multiple keywords are comma separated without space.
     */
    public function withOptinKeywords(string $optinKeywords): self
    {
        $self = clone $this;
        $self['optinKeywords'] = $optinKeywords;

        return $self;
    }

    /**
     * Subscriber opt-in message.
     */
    public function withOptinMessage(string $optinMessage): self
    {
        $self = clone $this;
        $self['optinMessage'] = $optinMessage;

        return $self;
    }

    /**
     * Subscriber opt-out keywords. Multiple keywords are comma separated without space.
     */
    public function withOptoutKeywords(string $optoutKeywords): self
    {
        $self = clone $this;
        $self['optoutKeywords'] = $optoutKeywords;

        return $self;
    }

    /**
     * Subscriber opt-out message.
     */
    public function withOptoutMessage(string $optoutMessage): self
    {
        $self = clone $this;
        $self['optoutMessage'] = $optoutMessage;

        return $self;
    }

    /**
     * Link to the campaign's privacy policy.
     */
    public function withPrivacyPolicyLink(string $privacyPolicyLink): self
    {
        $self = clone $this;
        $self['privacyPolicyLink'] = $privacyPolicyLink;

        return $self;
    }

    /**
     * Caller supplied campaign reference ID. If supplied, the value must be unique across all submitted campaigns. Can be used to prevent duplicate campaign registrations.
     */
    public function withReferenceID(string $referenceID): self
    {
        $self = clone $this;
        $self['referenceID'] = $referenceID;

        return $self;
    }

    /**
     * Alphanumeric identifier of the reseller that you want to associate with this campaign.
     */
    public function withResellerID(string $resellerID): self
    {
        $self = clone $this;
        $self['resellerID'] = $resellerID;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 1 or more message samples.
     */
    public function withSample1(string $sample1): self
    {
        $self = clone $this;
        $self['sample1'] = $sample1;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 2 or more message samples.
     */
    public function withSample2(string $sample2): self
    {
        $self = clone $this;
        $self['sample2'] = $sample2;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 3 or more message samples.
     */
    public function withSample3(string $sample3): self
    {
        $self = clone $this;
        $self['sample3'] = $sample3;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 4 or more message samples.
     */
    public function withSample4(string $sample4): self
    {
        $self = clone $this;
        $self['sample4'] = $sample4;

        return $self;
    }

    /**
     * Message sample. Some campaign tiers require 5 or more message samples.
     */
    public function withSample5(string $sample5): self
    {
        $self = clone $this;
        $self['sample5'] = $sample5;

        return $self;
    }

    /**
     * Current campaign status. Possible values: ACTIVE, EXPIRED. A newly created campaign defaults to ACTIVE status.
     */
    public function withStatus(string $status): self
    {
        $self = clone $this;
        $self['status'] = $status;

        return $self;
    }

    /**
     * Campaign submission status.
     *
     * @param SubmissionStatus|value-of<SubmissionStatus> $submissionStatus
     */
    public function withSubmissionStatus(
        SubmissionStatus|string $submissionStatus
    ): self {
        $self = clone $this;
        $self['submissionStatus'] = $submissionStatus;

        return $self;
    }

    /**
     * Does campaign responds to help keyword(s)?
     */
    public function withSubscriberHelp(bool $subscriberHelp): self
    {
        $self = clone $this;
        $self['subscriberHelp'] = $subscriberHelp;

        return $self;
    }

    /**
     * Does campaign require subscriber to opt-in before SMS is sent to subscriber?
     */
    public function withSubscriberOptin(bool $subscriberOptin): self
    {
        $self = clone $this;
        $self['subscriberOptin'] = $subscriberOptin;

        return $self;
    }

    /**
     * Does campaign support subscriber opt-out keyword(s)?
     */
    public function withSubscriberOptout(bool $subscriberOptout): self
    {
        $self = clone $this;
        $self['subscriberOptout'] = $subscriberOptout;

        return $self;
    }

    /**
     * Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/registry/enum/usecase` operation to retrieve list of valid sub-usecases.
     *
     * @param list<string> $subUsecases
     */
    public function withSubUsecases(array $subUsecases): self
    {
        $self = clone $this;
        $self['subUsecases'] = $subUsecases;

        return $self;
    }

    /**
     * Unique identifier assigned to the brand by the registry.
     */
    public function withTcrBrandID(string $tcrBrandID): self
    {
        $self = clone $this;
        $self['tcrBrandID'] = $tcrBrandID;

        return $self;
    }

    /**
     * Unique identifier assigned to the campaign by the registry.
     */
    public function withTcrCampaignID(string $tcrCampaignID): self
    {
        $self = clone $this;
        $self['tcrCampaignID'] = $tcrCampaignID;

        return $self;
    }

    /**
     * Is terms & conditions accepted?
     */
    public function withTermsAndConditions(bool $termsAndConditions): self
    {
        $self = clone $this;
        $self['termsAndConditions'] = $termsAndConditions;

        return $self;
    }

    /**
     * Link to the campaign's terms and conditions.
     */
    public function withTermsAndConditionsLink(
        string $termsAndConditionsLink
    ): self {
        $self = clone $this;
        $self['termsAndConditionsLink'] = $termsAndConditionsLink;

        return $self;
    }

    /**
     * Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase` operation to retrieve usecases available for given brand.
     */
    public function withUsecase(string $usecase): self
    {
        $self = clone $this;
        $self['usecase'] = $usecase;

        return $self;
    }

    /**
     * Business/industry segment of this campaign (Deprecated). Must be of defined valid types. Use `/registry/enum/vertical` operation to retrieve verticals available for given brand, vertical combination.
     *
     * This field is deprecated.
     */
    public function withVertical(string $vertical): self
    {
        $self = clone $this;
        $self['vertical'] = $vertical;

        return $self;
    }

    /**
     * Failover webhook to which campaign status updates are sent.
     */
    public function withWebhookFailoverURL(string $webhookFailoverURL): self
    {
        $self = clone $this;
        $self['webhookFailoverURL'] = $webhookFailoverURL;

        return $self;
    }

    /**
     * Webhook to which campaign status updates are sent.
     */
    public function withWebhookURL(string $webhookURL): self
    {
        $self = clone $this;
        $self['webhookURL'] = $webhookURL;

        return $self;
    }
}
