<?php

declare(strict_types=1);

namespace Telnyx\PortingOrdersExceptionType;

/**
 * Identifier of an exception type.
 */
enum Code: string
{
    case ACCOUNT_NUMBER_MISMATCH = 'ACCOUNT_NUMBER_MISMATCH';

    case AUTH_PERSON_MISMATCH = 'AUTH_PERSON_MISMATCH';

    case BTN_ATN_MISMATCH = 'BTN_ATN_MISMATCH';

    case ENTITY_NAME_MISMATCH = 'ENTITY_NAME_MISMATCH';

    case FOC_EXPIRED = 'FOC_EXPIRED';

    case FOC_REJECTED = 'FOC_REJECTED';

    case LOCATION_MISMATCH = 'LOCATION_MISMATCH';

    case LSR_PENDING = 'LSR_PENDING';

    case MAIN_BTN_PORTING = 'MAIN_BTN_PORTING';

    case OSP_IRRESPONSIVE = 'OSP_IRRESPONSIVE';

    case OTHER = 'OTHER';

    case PASSCODE_PIN_INVALID = 'PASSCODE_PIN_INVALID';

    case PHONE_NUMBER_HAS_SPECIAL_FEATURE = 'PHONE_NUMBER_HAS_SPECIAL_FEATURE';

    case PHONE_NUMBER_MISMATCH = 'PHONE_NUMBER_MISMATCH';

    case PHONE_NUMBER_NOT_PORTABLE = 'PHONE_NUMBER_NOT_PORTABLE';

    case PORT_TYPE_INCORRECT = 'PORT_TYPE_INCORRECT';

    case PORTING_ORDER_SPLIT_REQUIRED = 'PORTING_ORDER_SPLIT_REQUIRED';

    case POSTAL_CODE_MISMATCH = 'POSTAL_CODE_MISMATCH';

    case RATE_CENTER_NOT_PORTABLE = 'RATE_CENTER_NOT_PORTABLE';

    case SV_CONFLICT = 'SV_CONFLICT';

    case SV_UNKNOWN_FAILURE = 'SV_UNKNOWN_FAILURE';
}
