<?php

declare(strict_types=1);

namespace Telnyx\AI\Assistants\AssistantTool;

use Telnyx\Core\Attributes\Required;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Contracts\BaseModel;

/**
 * The send_message tool allows the assistant to send SMS or MMS messages to the end user. The 'to' and 'from' addresses are automatically determined from the conversation context, and the message text is generated by the assistant.
 *
 * @phpstan-type SendMessageToolShape = array{
 *   sendMessage: array<string,mixed>, type: 'send_message'
 * }
 */
final class SendMessageTool implements BaseModel
{
    /** @use SdkModel<SendMessageToolShape> */
    use SdkModel;

    /** @var 'send_message' $type */
    #[Required]
    public string $type = 'send_message';

    /** @var array<string,mixed> $sendMessage */
    #[Required('send_message', map: 'mixed')]
    public array $sendMessage;

    /**
     * `new SendMessageTool()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * SendMessageTool::with(sendMessage: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new SendMessageTool)->withSendMessage(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param array<string,mixed> $sendMessage
     */
    public static function with(array $sendMessage): self
    {
        $self = new self;

        $self['sendMessage'] = $sendMessage;

        return $self;
    }

    /**
     * @param array<string,mixed> $sendMessage
     */
    public function withSendMessage(array $sendMessage): self
    {
        $self = clone $this;
        $self['sendMessage'] = $sendMessage;

        return $self;
    }

    /**
     * @param 'send_message' $type
     */
    public function withType(string $type): self
    {
        $self = clone $this;
        $self['type'] = $type;

        return $self;
    }
}
