<?php

declare(strict_types=1);

namespace Telnyx\AI\Assistants\AssistantTool;

use Telnyx\AI\Assistants\AssistantTool\SendMessageTool\SendMessage;
use Telnyx\Core\Attributes\Optional;
use Telnyx\Core\Attributes\Required;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Contracts\BaseModel;

/**
 * The send_message tool allows the assistant to send SMS or MMS messages to the end user. The 'to' and 'from' addresses are automatically determined from the conversation context, and the message text is generated by the assistant unless a message_template is provided for runtime variable substitution.
 *
 * @phpstan-import-type SendMessageShape from \Telnyx\AI\Assistants\AssistantTool\SendMessageTool\SendMessage
 *
 * @phpstan-type SendMessageToolShape = array{
 *   sendMessage: SendMessage|SendMessageShape,
 *   type: 'send_message',
 *   shared?: bool|null,
 * }
 */
final class SendMessageTool implements BaseModel
{
    /** @use SdkModel<SendMessageToolShape> */
    use SdkModel;

    /** @var 'send_message' $type */
    #[Required]
    public string $type = 'send_message';

    #[Required('send_message')]
    public SendMessage $sendMessage;

    /**
     * Whether this tool comes from the shared Tools Library. Responses merge shared tools into `tools` with `shared: true`; inline tools carry `shared: false`. Read-only: set by the server, not accepted in requests. When updating an assistant, omit `shared: true` tools from the request `tools` array and manage them through `tool_ids` instead — re-sending their definitions creates an inline duplicate (rejected with error code 10015 when the type allows only one instance per assistant).
     */
    #[Optional]
    public ?bool $shared;

    /**
     * `new SendMessageTool()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * SendMessageTool::with(sendMessage: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new SendMessageTool)->withSendMessage(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param SendMessage|SendMessageShape $sendMessage
     */
    public static function with(
        SendMessage|array $sendMessage,
        ?bool $shared = null
    ): self {
        $self = new self;

        $self['sendMessage'] = $sendMessage;

        null !== $shared && $self['shared'] = $shared;

        return $self;
    }

    /**
     * @param SendMessage|SendMessageShape $sendMessage
     */
    public function withSendMessage(SendMessage|array $sendMessage): self
    {
        $self = clone $this;
        $self['sendMessage'] = $sendMessage;

        return $self;
    }

    /**
     * @param 'send_message' $type
     */
    public function withType(string $type): self
    {
        $self = clone $this;
        $self['type'] = $type;

        return $self;
    }

    /**
     * Whether this tool comes from the shared Tools Library. Responses merge shared tools into `tools` with `shared: true`; inline tools carry `shared: false`. Read-only: set by the server, not accepted in requests. When updating an assistant, omit `shared: true` tools from the request `tools` array and manage them through `tool_ids` instead — re-sending their definitions creates an inline duplicate (rejected with error code 10015 when the type allows only one instance per assistant).
     */
    public function withShared(bool $shared): self
    {
        $self = clone $this;
        $self['shared'] = $shared;

        return $self;
    }
}
