<?php

declare(strict_types=1);

namespace Telnyx\Calls\Actions\ActionAddAIAssistantMessagesParams\Message;

use Telnyx\Calls\Actions\ActionAddAIAssistantMessagesParams\Message\AssistantMessage\ToolCall;
use Telnyx\Core\Attributes\Optional;
use Telnyx\Core\Attributes\Required;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Contracts\BaseModel;

/**
 * Messages sent by the model in response to user messages.
 *
 * @phpstan-import-type ToolCallShape from \Telnyx\Calls\Actions\ActionAddAIAssistantMessagesParams\Message\AssistantMessage\ToolCall
 *
 * @phpstan-type AssistantMessageShape = array{
 *   role: 'assistant',
 *   content?: string|null,
 *   metadata?: array<string,mixed>|null,
 *   toolCalls?: list<ToolCall|ToolCallShape>|null,
 * }
 */
final class AssistantMessage implements BaseModel
{
    /** @use SdkModel<AssistantMessageShape> */
    use SdkModel;

    /**
     * The role of the messages author, in this case `assistant`.
     *
     * @var 'assistant' $role
     */
    #[Required]
    public string $role = 'assistant';

    /**
     * The contents of the assistant message. Required unless `tool_calls`.
     */
    #[Optional]
    public ?string $content;

    /**
     * Metadata to add to the message.
     *
     * @var array<string,mixed>|null $metadata
     */
    #[Optional(map: 'mixed')]
    public ?array $metadata;

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @var list<ToolCall>|null $toolCalls
     */
    #[Optional('tool_calls', list: ToolCall::class)]
    public ?array $toolCalls;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param array<string,mixed>|null $metadata
     * @param list<ToolCall|ToolCallShape>|null $toolCalls
     */
    public static function with(
        ?string $content = null,
        ?array $metadata = null,
        ?array $toolCalls = null
    ): self {
        $self = new self;

        null !== $content && $self['content'] = $content;
        null !== $metadata && $self['metadata'] = $metadata;
        null !== $toolCalls && $self['toolCalls'] = $toolCalls;

        return $self;
    }

    /**
     * The role of the messages author, in this case `assistant`.
     *
     * @param 'assistant' $role
     */
    public function withRole(string $role): self
    {
        $self = clone $this;
        $self['role'] = $role;

        return $self;
    }

    /**
     * The contents of the assistant message. Required unless `tool_calls`.
     */
    public function withContent(string $content): self
    {
        $self = clone $this;
        $self['content'] = $content;

        return $self;
    }

    /**
     * Metadata to add to the message.
     *
     * @param array<string,mixed> $metadata
     */
    public function withMetadata(array $metadata): self
    {
        $self = clone $this;
        $self['metadata'] = $metadata;

        return $self;
    }

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @param list<ToolCall|ToolCallShape> $toolCalls
     */
    public function withToolCalls(array $toolCalls): self
    {
        $self = clone $this;
        $self['toolCalls'] = $toolCalls;

        return $self;
    }
}
