<?php

declare(strict_types=1);

namespace Telnyx\ServiceContracts;

use Telnyx\Campaign\TelnyxCampaignCsp;
use Telnyx\RequestOptions;

use const Telnyx\Core\OMIT as omit;

interface CampaignBuilderContract
{
    /**
     * @api
     *
     * @param string $brandID alphanumeric identifier of the brand associated with this campaign
     * @param string $description summary description of this campaign
     * @param string $usecase Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase` operation to retrieve usecases available for given brand.
     * @param bool $ageGated age gated message content in campaign
     * @param bool $autoRenewal Campaign subscription auto-renewal option. If set to true, then campaign will automatically renewal at end of billing cycle.
     * @param bool $directLending Direct lending or loan arrangement
     * @param bool $embeddedLink Does message generated by the campaign include URL link in SMS?
     * @param string $embeddedLinkSample sample of an embedded link that will be sent to subscribers
     * @param bool $embeddedPhone Does message generated by the campaign include phone number in SMS?
     * @param string $helpKeywords Subscriber help keywords. Multiple keywords are comma separated without space.
     * @param string $helpMessage help message of the campaign
     * @param string $messageFlow message flow description
     * @param list<int> $mnoIDs Submit campaign to given list of MNOs by MNO's network ID. Default is all MNOs if no value provided.
     * @param bool $numberPool Does campaign utilize pool of phone numbers?
     * @param string $optinKeywords Subscriber opt-in keywords. Multiple keywords are comma separated without space.
     * @param string $optinMessage subscriber opt-in message
     * @param string $optoutKeywords Subscriber opt-out keywords. Multiple keywords are comma separated without space.
     * @param string $optoutMessage subscriber opt-out message
     * @param string $privacyPolicyLink link to the campaign's privacy policy
     * @param string $referenceID Caller supplied campaign reference ID. If supplied, the value must be unique across all submitted campaigns. Can be used to prevent duplicate campaign registrations.
     * @param string $resellerID alphanumeric identifier of the reseller that you want to associate with this campaign
     * @param string $sample1 Message sample. Some campaign tiers require 1 or more message samples.
     * @param string $sample2 Message sample. Some campaign tiers require 2 or more message samples.
     * @param string $sample3 Message sample. Some campaign tiers require 3 or more message samples.
     * @param string $sample4 Message sample. Some campaign tiers require 4 or more message samples.
     * @param string $sample5 Message sample. Some campaign tiers require 5 or more message samples.
     * @param bool $subscriberHelp Does campaign responds to help keyword(s)?
     * @param bool $subscriberOptin Does campaign require subscriber to opt-in before SMS is sent to subscriber?
     * @param bool $subscriberOptout Does campaign support subscriber opt-out keyword(s)?
     * @param list<string> $subUsecases Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/registry/enum/usecase` operation to retrieve list of valid sub-usecases
     * @param list<string> $tag tags to be set on the Campaign
     * @param bool $termsAndConditions Is terms and conditions accepted?
     * @param string $termsAndConditionsLink link to the campaign's terms and conditions
     * @param string $webhookFailoverURL failover webhook to which campaign status updates are sent
     * @param string $webhookURL webhook to which campaign status updates are sent
     *
     * @return mixed|TelnyxCampaignCsp
     */
    public function create(
        $brandID,
        $description,
        $usecase,
        $ageGated = omit,
        $autoRenewal = omit,
        $directLending = omit,
        $embeddedLink = omit,
        $embeddedLinkSample = omit,
        $embeddedPhone = omit,
        $helpKeywords = omit,
        $helpMessage = omit,
        $messageFlow = omit,
        $mnoIDs = omit,
        $numberPool = omit,
        $optinKeywords = omit,
        $optinMessage = omit,
        $optoutKeywords = omit,
        $optoutMessage = omit,
        $privacyPolicyLink = omit,
        $referenceID = omit,
        $resellerID = omit,
        $sample1 = omit,
        $sample2 = omit,
        $sample3 = omit,
        $sample4 = omit,
        $sample5 = omit,
        $subscriberHelp = omit,
        $subscriberOptin = omit,
        $subscriberOptout = omit,
        $subUsecases = omit,
        $tag = omit,
        $termsAndConditions = omit,
        $termsAndConditionsLink = omit,
        $webhookFailoverURL = omit,
        $webhookURL = omit,
        ?RequestOptions $requestOptions = null,
    ): mixed;
}
