<?php

declare(strict_types=1);

namespace Telnyx\ServiceContracts;

use Telnyx\AlphanumericSenderIDs\AlphanumericSenderID;
use Telnyx\Core\Exceptions\APIException;
use Telnyx\Core\Omitted;
use Telnyx\DefaultFlatPagination;
use Telnyx\MessagingProfileMetrics\MessagingMetricsTimeFrame;
use Telnyx\MessagingProfiles\MessagingMessagingProfile;
use Telnyx\MessagingProfiles\MessagingProfileCreateParams\WebhookAPIVersion;
use Telnyx\MessagingProfiles\MessagingProfileDeleteResponse;
use Telnyx\MessagingProfiles\MessagingProfileGetMetricsResponse;
use Telnyx\MessagingProfiles\MessagingProfileGetResponse;
use Telnyx\MessagingProfiles\MessagingProfileListParams\Filter;
use Telnyx\MessagingProfiles\MessagingProfileNewResponse;
use Telnyx\MessagingProfiles\MessagingProfileUpdateResponse;
use Telnyx\MessagingProfiles\NumberPoolSettings;
use Telnyx\MessagingProfiles\URLShortenerSettings;
use Telnyx\PhoneNumberWithMessagingSettings;
use Telnyx\RequestOptions;
use Telnyx\ShortCode;

/**
 * @phpstan-import-type FilterShape from \Telnyx\MessagingProfiles\MessagingProfileListParams\Filter
 * @phpstan-import-type NumberPoolSettingsShape from \Telnyx\MessagingProfiles\NumberPoolSettings
 * @phpstan-import-type URLShortenerSettingsShape from \Telnyx\MessagingProfiles\URLShortenerSettings
 * @phpstan-import-type RequestOpts from \Telnyx\RequestOptions
 */
interface MessagingProfilesContract
{
    /**
     * @api
     *
     * @param string $name a user friendly name for the messaging profile
     * @param list<string> $whitelistedDestinations Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]` all destinations will be allowed.
     * @param string|Omitted|null $aiAssistantID the AI assistant ID to associate with this messaging profile
     * @param string|Omitted|null $alphaSender the alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID
     * @param string $dailySpendLimit the maximum amount of money (in USD) that can be spent by this profile before midnight UTC
     * @param bool $dailySpendLimitEnabled whether to enforce the value configured by `daily_spend_limit`
     * @param bool $enabled specifies whether the messaging profile is enabled or not
     * @param string|Omitted|null $healthWebhookURL a URL to receive health check webhooks for numbers in this profile
     * @param bool $mmsFallBackToSMS enables SMS fallback for MMS messages
     * @param bool $mmsTranscoding enables automated resizing of MMS media
     * @param bool $mobileOnly send messages only to mobile phone numbers
     * @param Omitted|NumberPoolSettings|NumberPoolSettingsShape|null $numberPoolSettings Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     * @param string|Omitted|null $resourceGroupID the resource group ID to associate with this messaging profile
     * @param bool $smartEncoding Enables automatic character encoding optimization for SMS messages. When enabled, the system automatically selects the most efficient encoding (GSM-7 or UCS-2) based on message content to maximize character limits and minimize costs.
     * @param Omitted|URLShortenerSettings|URLShortenerSettingsShape|null $urlShortenerSettings The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion> $webhookAPIVersion determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format
     * @param string|Omitted|null $webhookFailoverURL the failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails
     * @param string|Omitted|null $webhookURL the URL where webhooks related to this messaging profile will be sent
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function create(
        string $name,
        array $whitelistedDestinations,
        string|Omitted|null $aiAssistantID = Omitted::VALUE,
        string|Omitted|null $alphaSender = Omitted::VALUE,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        bool $enabled = true,
        string|Omitted|null $healthWebhookURL = Omitted::VALUE,
        bool $mmsFallBackToSMS = false,
        bool $mmsTranscoding = false,
        bool $mobileOnly = false,
        Omitted|NumberPoolSettings|array|null $numberPoolSettings = Omitted::VALUE,
        string|Omitted|null $resourceGroupID = Omitted::VALUE,
        bool $smartEncoding = false,
        Omitted|URLShortenerSettings|array|null $urlShortenerSettings = Omitted::VALUE,
        WebhookAPIVersion|string $webhookAPIVersion = '2',
        string|Omitted|null $webhookFailoverURL = Omitted::VALUE,
        string|Omitted|null $webhookURL = Omitted::VALUE,
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileNewResponse;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function retrieve(
        string $messagingProfileID,
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileGetResponse;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param string|Omitted|null $aiAssistantID the ID of the AI assistant associated with this messaging profile
     * @param string|Omitted|null $alphaSender the alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID
     * @param string $dailySpendLimit the maximum amount of money (in USD) that can be spent by this profile before midnight UTC
     * @param bool $dailySpendLimitEnabled whether to enforce the value configured by `daily_spend_limit`
     * @param bool $enabled specifies whether the messaging profile is enabled or not
     * @param bool $mmsFallBackToSMS enables SMS fallback for MMS messages
     * @param bool $mmsTranscoding enables automated resizing of MMS media
     * @param bool $mobileOnly send messages only to mobile phone numbers
     * @param string $name a user friendly name for the messaging profile
     * @param Omitted|NumberPoolSettings|NumberPoolSettingsShape|null $numberPoolSettings Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     * @param bool $redactionEnabled Set to true to enable message content redaction on this profile, or false to disable it. Ignored if the organization is not on the redaction allowlist. See the [Message Redaction guide](/docs/messaging/messages/message-redaction) for what is redacted.
     * @param int $redactionLevel The redaction level to apply when redaction is enabled. 1: redact message records and reporting only. 2 (default): also redact inbound webhook payloads. See the [Message Redaction guide](/docs/messaging/messages/message-redaction).
     * @param bool $smartEncoding Enables automatic character encoding optimization for SMS messages. When enabled, the system automatically selects the most efficient encoding (GSM-7 or UCS-2) based on message content to maximize character limits and minimize costs.
     * @param Omitted|URLShortenerSettings|URLShortenerSettingsShape|null $urlShortenerSettings The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     * @param string $v1Secret secret used to authenticate with v1 endpoints
     * @param \Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion|value-of<\Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion> $webhookAPIVersion determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format
     * @param string|Omitted|null $webhookFailoverURL the failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails
     * @param string|Omitted|null $webhookURL the URL where webhooks related to this messaging profile will be sent
     * @param list<string> $whitelistedDestinations Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]`, all destinations will be allowed.
     *
     * This field is required if the messaging profile doesn't have it defined yet.
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function update(
        string $messagingProfileID,
        string|Omitted|null $aiAssistantID = Omitted::VALUE,
        string|Omitted|null $alphaSender = Omitted::VALUE,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        ?bool $enabled = null,
        bool $mmsFallBackToSMS = false,
        bool $mmsTranscoding = false,
        bool $mobileOnly = false,
        ?string $name = null,
        Omitted|NumberPoolSettings|array|null $numberPoolSettings = Omitted::VALUE,
        bool $redactionEnabled = false,
        int $redactionLevel = 2,
        bool $smartEncoding = false,
        Omitted|URLShortenerSettings|array|null $urlShortenerSettings = Omitted::VALUE,
        ?string $v1Secret = null,
        \Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion|string|null $webhookAPIVersion = null,
        string|Omitted|null $webhookFailoverURL = Omitted::VALUE,
        string|Omitted|null $webhookURL = Omitted::VALUE,
        ?array $whitelistedDestinations = null,
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileUpdateResponse;

    /**
     * @api
     *
     * @param Filter|FilterShape $filter Consolidated filter parameter (deepObject style). Originally: filter[name]
     * @param string $filterNameContains filter profiles by name containing the given string
     * @param string $filterNameEq filter profiles by exact name match
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultFlatPagination<MessagingMessagingProfile>
     *
     * @throws APIException
     */
    public function list(
        Filter|array|null $filter = null,
        ?string $filterNameContains = null,
        ?string $filterNameEq = null,
        ?int $pageNumber = null,
        ?int $pageSize = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultFlatPagination;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function delete(
        string $messagingProfileID,
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileDeleteResponse;

    /**
     * @api
     *
     * @param string $id the identifier of the messaging profile
     * @param int $pageNumber page number to retrieve (1-based)
     * @param int $pageSize number of items to return per page
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultFlatPagination<AlphanumericSenderID>
     *
     * @throws APIException
     */
    public function listAlphanumericSenderIDs(
        string $id,
        int $pageNumber = 1,
        int $pageSize = 20,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultFlatPagination;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultFlatPagination<PhoneNumberWithMessagingSettings>
     *
     * @throws APIException
     */
    public function listPhoneNumbers(
        string $messagingProfileID,
        ?int $pageNumber = null,
        ?int $pageSize = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultFlatPagination;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultFlatPagination<ShortCode>
     *
     * @throws APIException
     */
    public function listShortCodes(
        string $messagingProfileID,
        ?int $pageNumber = null,
        ?int $pageSize = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultFlatPagination;

    /**
     * @api
     *
     * @param string $id the identifier of the messaging profile
     * @param MessagingMetricsTimeFrame|value-of<MessagingMetricsTimeFrame> $timeFrame the time frame for metrics
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function retrieveMetrics(
        string $id,
        MessagingMetricsTimeFrame|string $timeFrame = '24h',
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileGetMetricsResponse;
}
