<?php

declare(strict_types=1);

namespace Telnyx\ServiceContracts;

use Telnyx\Core\Exceptions\APIException;
use Telnyx\DefaultPagination;
use Telnyx\MessagingProfiles\MessagingProfile;
use Telnyx\MessagingProfiles\MessagingProfileCreateParams\WebhookAPIVersion;
use Telnyx\MessagingProfiles\MessagingProfileDeleteResponse;
use Telnyx\MessagingProfiles\MessagingProfileGetResponse;
use Telnyx\MessagingProfiles\MessagingProfileListParams\Filter;
use Telnyx\MessagingProfiles\MessagingProfileListParams\Page;
use Telnyx\MessagingProfiles\MessagingProfileNewResponse;
use Telnyx\MessagingProfiles\MessagingProfileUpdateResponse;
use Telnyx\MessagingProfiles\NumberPoolSettings;
use Telnyx\MessagingProfiles\URLShortenerSettings;
use Telnyx\PhoneNumberWithMessagingSettings;
use Telnyx\RequestOptions;
use Telnyx\ShortCode;

/**
 * @phpstan-import-type FilterShape from \Telnyx\MessagingProfiles\MessagingProfileListParams\Filter
 * @phpstan-import-type PageShape from \Telnyx\MessagingProfiles\MessagingProfileListParams\Page
 * @phpstan-import-type PageShape from \Telnyx\MessagingProfiles\MessagingProfileListPhoneNumbersParams\Page as PageShape1
 * @phpstan-import-type PageShape from \Telnyx\MessagingProfiles\MessagingProfileListShortCodesParams\Page as PageShape2
 * @phpstan-import-type NumberPoolSettingsShape from \Telnyx\MessagingProfiles\NumberPoolSettings
 * @phpstan-import-type URLShortenerSettingsShape from \Telnyx\MessagingProfiles\URLShortenerSettings
 * @phpstan-import-type RequestOpts from \Telnyx\RequestOptions
 */
interface MessagingProfilesContract
{
    /**
     * @api
     *
     * @param string $name a user friendly name for the messaging profile
     * @param list<string> $whitelistedDestinations Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]` all destinations will be allowed.
     * @param string|null $alphaSender the alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID
     * @param string $dailySpendLimit the maximum amount of money (in USD) that can be spent by this profile before midnight UTC
     * @param bool $dailySpendLimitEnabled whether to enforce the value configured by `daily_spend_limit`
     * @param bool $enabled specifies whether the messaging profile is enabled or not
     * @param bool $mmsFallBackToSMS enables SMS fallback for MMS messages
     * @param bool $mmsTranscoding enables automated resizing of MMS media
     * @param bool $mobileOnly send messages only to mobile phone numbers
     * @param NumberPoolSettings|NumberPoolSettingsShape|null $numberPoolSettings Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     * @param bool $smartEncoding Enables automatic character encoding optimization for SMS messages. When enabled, the system automatically selects the most efficient encoding (GSM-7 or UCS-2) based on message content to maximize character limits and minimize costs.
     * @param URLShortenerSettings|URLShortenerSettingsShape|null $urlShortenerSettings The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion> $webhookAPIVersion determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format
     * @param string|null $webhookFailoverURL the failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails
     * @param string|null $webhookURL the URL where webhooks related to this messaging profile will be sent
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function create(
        string $name,
        array $whitelistedDestinations,
        ?string $alphaSender = null,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        bool $enabled = true,
        bool $mmsFallBackToSMS = false,
        bool $mmsTranscoding = false,
        bool $mobileOnly = false,
        NumberPoolSettings|array|null $numberPoolSettings = null,
        bool $smartEncoding = false,
        URLShortenerSettings|array|null $urlShortenerSettings = null,
        WebhookAPIVersion|string $webhookAPIVersion = '2',
        ?string $webhookFailoverURL = '',
        ?string $webhookURL = '',
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileNewResponse;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function retrieve(
        string $messagingProfileID,
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileGetResponse;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param string|null $alphaSender the alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID
     * @param string $dailySpendLimit the maximum amount of money (in USD) that can be spent by this profile before midnight UTC
     * @param bool $dailySpendLimitEnabled whether to enforce the value configured by `daily_spend_limit`
     * @param bool $enabled specifies whether the messaging profile is enabled or not
     * @param bool $mmsFallBackToSMS enables SMS fallback for MMS messages
     * @param bool $mmsTranscoding enables automated resizing of MMS media
     * @param bool $mobileOnly send messages only to mobile phone numbers
     * @param string $name a user friendly name for the messaging profile
     * @param NumberPoolSettings|NumberPoolSettingsShape|null $numberPoolSettings Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     * @param bool $smartEncoding Enables automatic character encoding optimization for SMS messages. When enabled, the system automatically selects the most efficient encoding (GSM-7 or UCS-2) based on message content to maximize character limits and minimize costs.
     * @param URLShortenerSettings|URLShortenerSettingsShape|null $urlShortenerSettings The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     * @param string $v1Secret secret used to authenticate with v1 endpoints
     * @param \Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion|value-of<\Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion> $webhookAPIVersion determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format
     * @param string|null $webhookFailoverURL the failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails
     * @param string|null $webhookURL the URL where webhooks related to this messaging profile will be sent
     * @param list<string> $whitelistedDestinations Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]`, all destinations will be allowed.
     *
     * This field is required if the messaging profile doesn't have it defined yet.
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function update(
        string $messagingProfileID,
        ?string $alphaSender = null,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        ?bool $enabled = null,
        bool $mmsFallBackToSMS = false,
        bool $mmsTranscoding = false,
        bool $mobileOnly = false,
        ?string $name = null,
        NumberPoolSettings|array|null $numberPoolSettings = null,
        bool $smartEncoding = false,
        URLShortenerSettings|array|null $urlShortenerSettings = null,
        ?string $v1Secret = null,
        \Telnyx\MessagingProfiles\MessagingProfileUpdateParams\WebhookAPIVersion|string|null $webhookAPIVersion = null,
        ?string $webhookFailoverURL = null,
        ?string $webhookURL = null,
        ?array $whitelistedDestinations = null,
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileUpdateResponse;

    /**
     * @api
     *
     * @param Filter|FilterShape $filter Consolidated filter parameter (deepObject style). Originally: filter[name]
     * @param Page|PageShape $page Consolidated page parameter (deepObject style). Originally: page[number], page[size]
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultPagination<MessagingProfile>
     *
     * @throws APIException
     */
    public function list(
        Filter|array|null $filter = null,
        Page|array|null $page = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultPagination;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function delete(
        string $messagingProfileID,
        RequestOptions|array|null $requestOptions = null,
    ): MessagingProfileDeleteResponse;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param \Telnyx\MessagingProfiles\MessagingProfileListPhoneNumbersParams\Page|PageShape1 $page Consolidated page parameter (deepObject style). Originally: page[number], page[size]
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultPagination<PhoneNumberWithMessagingSettings>
     *
     * @throws APIException
     */
    public function listPhoneNumbers(
        string $messagingProfileID,
        \Telnyx\MessagingProfiles\MessagingProfileListPhoneNumbersParams\Page|array|null $page = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultPagination;

    /**
     * @api
     *
     * @param string $messagingProfileID The id of the messaging profile to retrieve
     * @param \Telnyx\MessagingProfiles\MessagingProfileListShortCodesParams\Page|PageShape2 $page Consolidated page parameter (deepObject style). Originally: page[number], page[size]
     * @param RequestOpts|null $requestOptions
     *
     * @return DefaultPagination<ShortCode>
     *
     * @throws APIException
     */
    public function listShortCodes(
        string $messagingProfileID,
        \Telnyx\MessagingProfiles\MessagingProfileListShortCodesParams\Page|array|null $page = null,
        RequestOptions|array|null $requestOptions = null,
    ): DefaultPagination;
}
