<?php

declare(strict_types=1);

namespace Telnyx\MessagingProfiles;

use Telnyx\Core\Attributes\Optional;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Contracts\BaseModel;
use Telnyx\MessagingProfiles\MessagingProfile\RecordType;
use Telnyx\MessagingProfiles\MessagingProfile\WebhookAPIVersion;

/**
 * @phpstan-type MessagingProfileShape = array{
 *   id?: string|null,
 *   alphaSender?: string|null,
 *   createdAt?: \DateTimeInterface|null,
 *   dailySpendLimit?: string|null,
 *   dailySpendLimitEnabled?: bool|null,
 *   enabled?: bool|null,
 *   healthWebhookURL?: string|null,
 *   mmsFallBackToSMS?: bool|null,
 *   mmsTranscoding?: bool|null,
 *   mobileOnly?: bool|null,
 *   name?: string|null,
 *   numberPoolSettings?: NumberPoolSettings|null,
 *   recordType?: value-of<RecordType>|null,
 *   redactionEnabled?: bool|null,
 *   redactionLevel?: int|null,
 *   updatedAt?: \DateTimeInterface|null,
 *   urlShortenerSettings?: URLShortenerSettings|null,
 *   v1Secret?: string|null,
 *   webhookAPIVersion?: value-of<WebhookAPIVersion>|null,
 *   webhookFailoverURL?: string|null,
 *   webhookURL?: string|null,
 *   whitelistedDestinations?: list<string>|null,
 * }
 */
final class MessagingProfile implements BaseModel
{
    /** @use SdkModel<MessagingProfileShape> */
    use SdkModel;

    /**
     * Identifies the type of resource.
     */
    #[Optional]
    public ?string $id;

    /**
     * The alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID.
     */
    #[Optional('alpha_sender', nullable: true)]
    public ?string $alphaSender;

    /**
     * ISO 8601 formatted date indicating when the resource was created.
     */
    #[Optional('created_at')]
    public ?\DateTimeInterface $createdAt;

    /**
     * The maximum amount of money (in USD) that can be spent by this profile before midnight UTC.
     */
    #[Optional('daily_spend_limit')]
    public ?string $dailySpendLimit;

    /**
     * Whether to enforce the value configured by `daily_spend_limit`.
     */
    #[Optional('daily_spend_limit_enabled')]
    public ?bool $dailySpendLimitEnabled;

    /**
     * Specifies whether the messaging profile is enabled or not.
     */
    #[Optional]
    public ?bool $enabled;

    /**
     * DEPRECATED: health check url service checking.
     */
    #[Optional('health_webhook_url', nullable: true)]
    public ?string $healthWebhookURL;

    /**
     * enables SMS fallback for MMS messages.
     */
    #[Optional('mms_fall_back_to_sms')]
    public ?bool $mmsFallBackToSMS;

    /**
     * enables automated resizing of MMS media.
     */
    #[Optional('mms_transcoding')]
    public ?bool $mmsTranscoding;

    /**
     * Send messages only to mobile phone numbers.
     */
    #[Optional('mobile_only')]
    public ?bool $mobileOnly;

    /**
     * A user friendly name for the messaging profile.
     */
    #[Optional]
    public ?string $name;

    /**
     * Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     */
    #[Optional('number_pool_settings', nullable: true)]
    public ?NumberPoolSettings $numberPoolSettings;

    /**
     * Identifies the type of the resource.
     *
     * @var value-of<RecordType>|null $recordType
     */
    #[Optional('record_type', enum: RecordType::class)]
    public ?string $recordType;

    /**
     * Indicates whether message content redaction is enabled for this profile.
     */
    #[Optional('redaction_enabled')]
    public ?bool $redactionEnabled;

    /**
     * Determines how much information is redacted in messages for privacy or compliance purposes.
     */
    #[Optional('redaction_level')]
    public ?int $redactionLevel;

    /**
     * ISO 8601 formatted date indicating when the resource was updated.
     */
    #[Optional('updated_at')]
    public ?\DateTimeInterface $updatedAt;

    /**
     * The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     */
    #[Optional('url_shortener_settings', nullable: true)]
    public ?URLShortenerSettings $urlShortenerSettings;

    /**
     * Secret used to authenticate with v1 endpoints.
     */
    #[Optional('v1_secret')]
    public ?string $v1Secret;

    /**
     * Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
     *
     * @var value-of<WebhookAPIVersion>|null $webhookAPIVersion
     */
    #[Optional('webhook_api_version', enum: WebhookAPIVersion::class)]
    public ?string $webhookAPIVersion;

    /**
     * The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
     */
    #[Optional('webhook_failover_url', nullable: true)]
    public ?string $webhookFailoverURL;

    /**
     * The URL where webhooks related to this messaging profile will be sent.
     */
    #[Optional('webhook_url', nullable: true)]
    public ?string $webhookURL;

    /**
     * Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]`, all destinations will be allowed.
     *
     * @var list<string>|null $whitelistedDestinations
     */
    #[Optional('whitelisted_destinations', list: 'string')]
    public ?array $whitelistedDestinations;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param NumberPoolSettings|array{
     *   longCodeWeight: float,
     *   skipUnhealthy: bool,
     *   tollFreeWeight: float,
     *   geomatch?: bool|null,
     *   stickySender?: bool|null,
     * }|null $numberPoolSettings
     * @param RecordType|value-of<RecordType> $recordType
     * @param URLShortenerSettings|array{
     *   domain: string,
     *   prefix?: string|null,
     *   replaceBlacklistOnly?: bool|null,
     *   sendWebhooks?: bool|null,
     * }|null $urlShortenerSettings
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion> $webhookAPIVersion
     * @param list<string> $whitelistedDestinations
     */
    public static function with(
        ?string $id = null,
        ?string $alphaSender = null,
        ?\DateTimeInterface $createdAt = null,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        ?bool $enabled = null,
        ?string $healthWebhookURL = null,
        ?bool $mmsFallBackToSMS = null,
        ?bool $mmsTranscoding = null,
        ?bool $mobileOnly = null,
        ?string $name = null,
        NumberPoolSettings|array|null $numberPoolSettings = null,
        RecordType|string|null $recordType = null,
        ?bool $redactionEnabled = null,
        ?int $redactionLevel = null,
        ?\DateTimeInterface $updatedAt = null,
        URLShortenerSettings|array|null $urlShortenerSettings = null,
        ?string $v1Secret = null,
        WebhookAPIVersion|string|null $webhookAPIVersion = null,
        ?string $webhookFailoverURL = null,
        ?string $webhookURL = null,
        ?array $whitelistedDestinations = null,
    ): self {
        $obj = new self;

        null !== $id && $obj['id'] = $id;
        null !== $alphaSender && $obj['alphaSender'] = $alphaSender;
        null !== $createdAt && $obj['createdAt'] = $createdAt;
        null !== $dailySpendLimit && $obj['dailySpendLimit'] = $dailySpendLimit;
        null !== $dailySpendLimitEnabled && $obj['dailySpendLimitEnabled'] = $dailySpendLimitEnabled;
        null !== $enabled && $obj['enabled'] = $enabled;
        null !== $healthWebhookURL && $obj['healthWebhookURL'] = $healthWebhookURL;
        null !== $mmsFallBackToSMS && $obj['mmsFallBackToSMS'] = $mmsFallBackToSMS;
        null !== $mmsTranscoding && $obj['mmsTranscoding'] = $mmsTranscoding;
        null !== $mobileOnly && $obj['mobileOnly'] = $mobileOnly;
        null !== $name && $obj['name'] = $name;
        null !== $numberPoolSettings && $obj['numberPoolSettings'] = $numberPoolSettings;
        null !== $recordType && $obj['recordType'] = $recordType;
        null !== $redactionEnabled && $obj['redactionEnabled'] = $redactionEnabled;
        null !== $redactionLevel && $obj['redactionLevel'] = $redactionLevel;
        null !== $updatedAt && $obj['updatedAt'] = $updatedAt;
        null !== $urlShortenerSettings && $obj['urlShortenerSettings'] = $urlShortenerSettings;
        null !== $v1Secret && $obj['v1Secret'] = $v1Secret;
        null !== $webhookAPIVersion && $obj['webhookAPIVersion'] = $webhookAPIVersion;
        null !== $webhookFailoverURL && $obj['webhookFailoverURL'] = $webhookFailoverURL;
        null !== $webhookURL && $obj['webhookURL'] = $webhookURL;
        null !== $whitelistedDestinations && $obj['whitelistedDestinations'] = $whitelistedDestinations;

        return $obj;
    }

    /**
     * Identifies the type of resource.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj['id'] = $id;

        return $obj;
    }

    /**
     * The alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID.
     */
    public function withAlphaSender(?string $alphaSender): self
    {
        $obj = clone $this;
        $obj['alphaSender'] = $alphaSender;

        return $obj;
    }

    /**
     * ISO 8601 formatted date indicating when the resource was created.
     */
    public function withCreatedAt(\DateTimeInterface $createdAt): self
    {
        $obj = clone $this;
        $obj['createdAt'] = $createdAt;

        return $obj;
    }

    /**
     * The maximum amount of money (in USD) that can be spent by this profile before midnight UTC.
     */
    public function withDailySpendLimit(string $dailySpendLimit): self
    {
        $obj = clone $this;
        $obj['dailySpendLimit'] = $dailySpendLimit;

        return $obj;
    }

    /**
     * Whether to enforce the value configured by `daily_spend_limit`.
     */
    public function withDailySpendLimitEnabled(
        bool $dailySpendLimitEnabled
    ): self {
        $obj = clone $this;
        $obj['dailySpendLimitEnabled'] = $dailySpendLimitEnabled;

        return $obj;
    }

    /**
     * Specifies whether the messaging profile is enabled or not.
     */
    public function withEnabled(bool $enabled): self
    {
        $obj = clone $this;
        $obj['enabled'] = $enabled;

        return $obj;
    }

    /**
     * DEPRECATED: health check url service checking.
     */
    public function withHealthWebhookURL(?string $healthWebhookURL): self
    {
        $obj = clone $this;
        $obj['healthWebhookURL'] = $healthWebhookURL;

        return $obj;
    }

    /**
     * enables SMS fallback for MMS messages.
     */
    public function withMmsFallBackToSMS(bool $mmsFallBackToSMS): self
    {
        $obj = clone $this;
        $obj['mmsFallBackToSMS'] = $mmsFallBackToSMS;

        return $obj;
    }

    /**
     * enables automated resizing of MMS media.
     */
    public function withMmsTranscoding(bool $mmsTranscoding): self
    {
        $obj = clone $this;
        $obj['mmsTranscoding'] = $mmsTranscoding;

        return $obj;
    }

    /**
     * Send messages only to mobile phone numbers.
     */
    public function withMobileOnly(bool $mobileOnly): self
    {
        $obj = clone $this;
        $obj['mobileOnly'] = $mobileOnly;

        return $obj;
    }

    /**
     * A user friendly name for the messaging profile.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj['name'] = $name;

        return $obj;
    }

    /**
     * Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     *
     * @param NumberPoolSettings|array{
     *   longCodeWeight: float,
     *   skipUnhealthy: bool,
     *   tollFreeWeight: float,
     *   geomatch?: bool|null,
     *   stickySender?: bool|null,
     * }|null $numberPoolSettings
     */
    public function withNumberPoolSettings(
        NumberPoolSettings|array|null $numberPoolSettings
    ): self {
        $obj = clone $this;
        $obj['numberPoolSettings'] = $numberPoolSettings;

        return $obj;
    }

    /**
     * Identifies the type of the resource.
     *
     * @param RecordType|value-of<RecordType> $recordType
     */
    public function withRecordType(RecordType|string $recordType): self
    {
        $obj = clone $this;
        $obj['recordType'] = $recordType;

        return $obj;
    }

    /**
     * Indicates whether message content redaction is enabled for this profile.
     */
    public function withRedactionEnabled(bool $redactionEnabled): self
    {
        $obj = clone $this;
        $obj['redactionEnabled'] = $redactionEnabled;

        return $obj;
    }

    /**
     * Determines how much information is redacted in messages for privacy or compliance purposes.
     */
    public function withRedactionLevel(int $redactionLevel): self
    {
        $obj = clone $this;
        $obj['redactionLevel'] = $redactionLevel;

        return $obj;
    }

    /**
     * ISO 8601 formatted date indicating when the resource was updated.
     */
    public function withUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $obj = clone $this;
        $obj['updatedAt'] = $updatedAt;

        return $obj;
    }

    /**
     * The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     *
     * @param URLShortenerSettings|array{
     *   domain: string,
     *   prefix?: string|null,
     *   replaceBlacklistOnly?: bool|null,
     *   sendWebhooks?: bool|null,
     * }|null $urlShortenerSettings
     */
    public function withURLShortenerSettings(
        URLShortenerSettings|array|null $urlShortenerSettings
    ): self {
        $obj = clone $this;
        $obj['urlShortenerSettings'] = $urlShortenerSettings;

        return $obj;
    }

    /**
     * Secret used to authenticate with v1 endpoints.
     */
    public function withV1Secret(string $v1Secret): self
    {
        $obj = clone $this;
        $obj['v1Secret'] = $v1Secret;

        return $obj;
    }

    /**
     * Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
     *
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion> $webhookAPIVersion
     */
    public function withWebhookAPIVersion(
        WebhookAPIVersion|string $webhookAPIVersion
    ): self {
        $obj = clone $this;
        $obj['webhookAPIVersion'] = $webhookAPIVersion;

        return $obj;
    }

    /**
     * The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
     */
    public function withWebhookFailoverURL(?string $webhookFailoverURL): self
    {
        $obj = clone $this;
        $obj['webhookFailoverURL'] = $webhookFailoverURL;

        return $obj;
    }

    /**
     * The URL where webhooks related to this messaging profile will be sent.
     */
    public function withWebhookURL(?string $webhookURL): self
    {
        $obj = clone $this;
        $obj['webhookURL'] = $webhookURL;

        return $obj;
    }

    /**
     * Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]`, all destinations will be allowed.
     *
     * @param list<string> $whitelistedDestinations
     */
    public function withWhitelistedDestinations(
        array $whitelistedDestinations
    ): self {
        $obj = clone $this;
        $obj['whitelistedDestinations'] = $whitelistedDestinations;

        return $obj;
    }
}
