<?php

declare(strict_types=1);

namespace Telnyx\MessagingProfiles;

use Telnyx\Core\Attributes\Optional;
use Telnyx\Core\Attributes\Required;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Concerns\SdkParams;
use Telnyx\Core\Contracts\BaseModel;
use Telnyx\MessagingProfiles\MessagingProfileCreateParams\WebhookAPIVersion;

/**
 * Create a messaging profile.
 *
 * @see Telnyx\Services\MessagingProfilesService::create()
 *
 * @phpstan-import-type NumberPoolSettingsShape from \Telnyx\MessagingProfiles\NumberPoolSettings
 * @phpstan-import-type URLShortenerSettingsShape from \Telnyx\MessagingProfiles\URLShortenerSettings
 *
 * @phpstan-type MessagingProfileCreateParamsShape = array{
 *   name: string,
 *   whitelistedDestinations: list<string>,
 *   alphaSender?: string|null,
 *   dailySpendLimit?: string|null,
 *   dailySpendLimitEnabled?: bool|null,
 *   enabled?: bool|null,
 *   mmsFallBackToSMS?: bool|null,
 *   mmsTranscoding?: bool|null,
 *   mobileOnly?: bool|null,
 *   numberPoolSettings?: null|NumberPoolSettings|NumberPoolSettingsShape,
 *   urlShortenerSettings?: null|URLShortenerSettings|URLShortenerSettingsShape,
 *   webhookAPIVersion?: null|WebhookAPIVersion|value-of<WebhookAPIVersion>,
 *   webhookFailoverURL?: string|null,
 *   webhookURL?: string|null,
 * }
 */
final class MessagingProfileCreateParams implements BaseModel
{
    /** @use SdkModel<MessagingProfileCreateParamsShape> */
    use SdkModel;
    use SdkParams;

    /**
     * A user friendly name for the messaging profile.
     */
    #[Required]
    public string $name;

    /**
     * Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]` all destinations will be allowed.
     *
     * @var list<string> $whitelistedDestinations
     */
    #[Required('whitelisted_destinations', list: 'string')]
    public array $whitelistedDestinations;

    /**
     * The alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID.
     */
    #[Optional('alpha_sender', nullable: true)]
    public ?string $alphaSender;

    /**
     * The maximum amount of money (in USD) that can be spent by this profile before midnight UTC.
     */
    #[Optional('daily_spend_limit')]
    public ?string $dailySpendLimit;

    /**
     * Whether to enforce the value configured by `daily_spend_limit`.
     */
    #[Optional('daily_spend_limit_enabled')]
    public ?bool $dailySpendLimitEnabled;

    /**
     * Specifies whether the messaging profile is enabled or not.
     */
    #[Optional]
    public ?bool $enabled;

    /**
     * enables SMS fallback for MMS messages.
     */
    #[Optional('mms_fall_back_to_sms')]
    public ?bool $mmsFallBackToSMS;

    /**
     * enables automated resizing of MMS media.
     */
    #[Optional('mms_transcoding')]
    public ?bool $mmsTranscoding;

    /**
     * Send messages only to mobile phone numbers.
     */
    #[Optional('mobile_only')]
    public ?bool $mobileOnly;

    /**
     * Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     */
    #[Optional('number_pool_settings', nullable: true)]
    public ?NumberPoolSettings $numberPoolSettings;

    /**
     * The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     */
    #[Optional('url_shortener_settings', nullable: true)]
    public ?URLShortenerSettings $urlShortenerSettings;

    /**
     * Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
     *
     * @var value-of<WebhookAPIVersion>|null $webhookAPIVersion
     */
    #[Optional('webhook_api_version', enum: WebhookAPIVersion::class)]
    public ?string $webhookAPIVersion;

    /**
     * The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
     */
    #[Optional('webhook_failover_url', nullable: true)]
    public ?string $webhookFailoverURL;

    /**
     * The URL where webhooks related to this messaging profile will be sent.
     */
    #[Optional('webhook_url', nullable: true)]
    public ?string $webhookURL;

    /**
     * `new MessagingProfileCreateParams()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * MessagingProfileCreateParams::with(name: ..., whitelistedDestinations: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new MessagingProfileCreateParams)
     *   ->withName(...)
     *   ->withWhitelistedDestinations(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<string> $whitelistedDestinations
     * @param NumberPoolSettings|NumberPoolSettingsShape|null $numberPoolSettings
     * @param URLShortenerSettings|URLShortenerSettingsShape|null $urlShortenerSettings
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion>|null $webhookAPIVersion
     */
    public static function with(
        string $name,
        array $whitelistedDestinations,
        ?string $alphaSender = null,
        ?string $dailySpendLimit = null,
        ?bool $dailySpendLimitEnabled = null,
        ?bool $enabled = null,
        ?bool $mmsFallBackToSMS = null,
        ?bool $mmsTranscoding = null,
        ?bool $mobileOnly = null,
        NumberPoolSettings|array|null $numberPoolSettings = null,
        URLShortenerSettings|array|null $urlShortenerSettings = null,
        WebhookAPIVersion|string|null $webhookAPIVersion = null,
        ?string $webhookFailoverURL = null,
        ?string $webhookURL = null,
    ): self {
        $self = new self;

        $self['name'] = $name;
        $self['whitelistedDestinations'] = $whitelistedDestinations;

        null !== $alphaSender && $self['alphaSender'] = $alphaSender;
        null !== $dailySpendLimit && $self['dailySpendLimit'] = $dailySpendLimit;
        null !== $dailySpendLimitEnabled && $self['dailySpendLimitEnabled'] = $dailySpendLimitEnabled;
        null !== $enabled && $self['enabled'] = $enabled;
        null !== $mmsFallBackToSMS && $self['mmsFallBackToSMS'] = $mmsFallBackToSMS;
        null !== $mmsTranscoding && $self['mmsTranscoding'] = $mmsTranscoding;
        null !== $mobileOnly && $self['mobileOnly'] = $mobileOnly;
        null !== $numberPoolSettings && $self['numberPoolSettings'] = $numberPoolSettings;
        null !== $urlShortenerSettings && $self['urlShortenerSettings'] = $urlShortenerSettings;
        null !== $webhookAPIVersion && $self['webhookAPIVersion'] = $webhookAPIVersion;
        null !== $webhookFailoverURL && $self['webhookFailoverURL'] = $webhookFailoverURL;
        null !== $webhookURL && $self['webhookURL'] = $webhookURL;

        return $self;
    }

    /**
     * A user friendly name for the messaging profile.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }

    /**
     * Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]` all destinations will be allowed.
     *
     * @param list<string> $whitelistedDestinations
     */
    public function withWhitelistedDestinations(
        array $whitelistedDestinations
    ): self {
        $self = clone $this;
        $self['whitelistedDestinations'] = $whitelistedDestinations;

        return $self;
    }

    /**
     * The alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID.
     */
    public function withAlphaSender(?string $alphaSender): self
    {
        $self = clone $this;
        $self['alphaSender'] = $alphaSender;

        return $self;
    }

    /**
     * The maximum amount of money (in USD) that can be spent by this profile before midnight UTC.
     */
    public function withDailySpendLimit(string $dailySpendLimit): self
    {
        $self = clone $this;
        $self['dailySpendLimit'] = $dailySpendLimit;

        return $self;
    }

    /**
     * Whether to enforce the value configured by `daily_spend_limit`.
     */
    public function withDailySpendLimitEnabled(
        bool $dailySpendLimitEnabled
    ): self {
        $self = clone $this;
        $self['dailySpendLimitEnabled'] = $dailySpendLimitEnabled;

        return $self;
    }

    /**
     * Specifies whether the messaging profile is enabled or not.
     */
    public function withEnabled(bool $enabled): self
    {
        $self = clone $this;
        $self['enabled'] = $enabled;

        return $self;
    }

    /**
     * enables SMS fallback for MMS messages.
     */
    public function withMmsFallBackToSMS(bool $mmsFallBackToSMS): self
    {
        $self = clone $this;
        $self['mmsFallBackToSMS'] = $mmsFallBackToSMS;

        return $self;
    }

    /**
     * enables automated resizing of MMS media.
     */
    public function withMmsTranscoding(bool $mmsTranscoding): self
    {
        $self = clone $this;
        $self['mmsTranscoding'] = $mmsTranscoding;

        return $self;
    }

    /**
     * Send messages only to mobile phone numbers.
     */
    public function withMobileOnly(bool $mobileOnly): self
    {
        $self = clone $this;
        $self['mobileOnly'] = $mobileOnly;

        return $self;
    }

    /**
     * Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     *
     * @param NumberPoolSettings|NumberPoolSettingsShape|null $numberPoolSettings
     */
    public function withNumberPoolSettings(
        NumberPoolSettings|array|null $numberPoolSettings
    ): self {
        $self = clone $this;
        $self['numberPoolSettings'] = $numberPoolSettings;

        return $self;
    }

    /**
     * The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     *
     * @param URLShortenerSettings|URLShortenerSettingsShape|null $urlShortenerSettings
     */
    public function withURLShortenerSettings(
        URLShortenerSettings|array|null $urlShortenerSettings
    ): self {
        $self = clone $this;
        $self['urlShortenerSettings'] = $urlShortenerSettings;

        return $self;
    }

    /**
     * Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
     *
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion> $webhookAPIVersion
     */
    public function withWebhookAPIVersion(
        WebhookAPIVersion|string $webhookAPIVersion
    ): self {
        $self = clone $this;
        $self['webhookAPIVersion'] = $webhookAPIVersion;

        return $self;
    }

    /**
     * The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
     */
    public function withWebhookFailoverURL(?string $webhookFailoverURL): self
    {
        $self = clone $this;
        $self['webhookFailoverURL'] = $webhookFailoverURL;

        return $self;
    }

    /**
     * The URL where webhooks related to this messaging profile will be sent.
     */
    public function withWebhookURL(?string $webhookURL): self
    {
        $self = clone $this;
        $self['webhookURL'] = $webhookURL;

        return $self;
    }
}
