<?php

declare(strict_types=1);

namespace Telnyx\MessagingProfiles;

use Telnyx\Core\Attributes\Api;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Concerns\SdkParams;
use Telnyx\Core\Contracts\BaseModel;
use Telnyx\MessagingProfiles\MessagingProfileCreateParams\WebhookAPIVersion;

/**
 * Create a messaging profile.
 *
 * @see Telnyx\Services\MessagingProfilesService::create()
 *
 * @phpstan-type MessagingProfileCreateParamsShape = array{
 *   name: string,
 *   whitelisted_destinations: list<string>,
 *   alpha_sender?: string|null,
 *   daily_spend_limit?: string,
 *   daily_spend_limit_enabled?: bool,
 *   enabled?: bool,
 *   mms_fall_back_to_sms?: bool,
 *   mms_transcoding?: bool,
 *   mobile_only?: bool,
 *   number_pool_settings?: NumberPoolSettings|null,
 *   url_shortener_settings?: URLShortenerSettings|null,
 *   webhook_api_version?: WebhookAPIVersion|value-of<WebhookAPIVersion>,
 *   webhook_failover_url?: string|null,
 *   webhook_url?: string|null,
 * }
 */
final class MessagingProfileCreateParams implements BaseModel
{
    /** @use SdkModel<MessagingProfileCreateParamsShape> */
    use SdkModel;
    use SdkParams;

    /**
     * A user friendly name for the messaging profile.
     */
    #[Api]
    public string $name;

    /**
     * Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]` all destinations will be allowed.
     *
     * @var list<string> $whitelisted_destinations
     */
    #[Api(list: 'string')]
    public array $whitelisted_destinations;

    /**
     * The alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID.
     */
    #[Api(nullable: true, optional: true)]
    public ?string $alpha_sender;

    /**
     * The maximum amount of money (in USD) that can be spent by this profile before midnight UTC.
     */
    #[Api(optional: true)]
    public ?string $daily_spend_limit;

    /**
     * Whether to enforce the value configured by `daily_spend_limit`.
     */
    #[Api(optional: true)]
    public ?bool $daily_spend_limit_enabled;

    /**
     * Specifies whether the messaging profile is enabled or not.
     */
    #[Api(optional: true)]
    public ?bool $enabled;

    /**
     * enables SMS fallback for MMS messages.
     */
    #[Api(optional: true)]
    public ?bool $mms_fall_back_to_sms;

    /**
     * enables automated resizing of MMS media.
     */
    #[Api(optional: true)]
    public ?bool $mms_transcoding;

    /**
     * Send messages only to mobile phone numbers.
     */
    #[Api(optional: true)]
    public ?bool $mobile_only;

    /**
     * Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     */
    #[Api(nullable: true, optional: true)]
    public ?NumberPoolSettings $number_pool_settings;

    /**
     * The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     */
    #[Api(nullable: true, optional: true)]
    public ?URLShortenerSettings $url_shortener_settings;

    /**
     * Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
     *
     * @var value-of<WebhookAPIVersion>|null $webhook_api_version
     */
    #[Api(enum: WebhookAPIVersion::class, optional: true)]
    public ?string $webhook_api_version;

    /**
     * The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
     */
    #[Api(nullable: true, optional: true)]
    public ?string $webhook_failover_url;

    /**
     * The URL where webhooks related to this messaging profile will be sent.
     */
    #[Api(nullable: true, optional: true)]
    public ?string $webhook_url;

    /**
     * `new MessagingProfileCreateParams()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * MessagingProfileCreateParams::with(name: ..., whitelisted_destinations: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new MessagingProfileCreateParams)
     *   ->withName(...)
     *   ->withWhitelistedDestinations(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<string> $whitelisted_destinations
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion> $webhook_api_version
     */
    public static function with(
        string $name,
        array $whitelisted_destinations,
        ?string $alpha_sender = null,
        ?string $daily_spend_limit = null,
        ?bool $daily_spend_limit_enabled = null,
        ?bool $enabled = null,
        ?bool $mms_fall_back_to_sms = null,
        ?bool $mms_transcoding = null,
        ?bool $mobile_only = null,
        ?NumberPoolSettings $number_pool_settings = null,
        ?URLShortenerSettings $url_shortener_settings = null,
        WebhookAPIVersion|string|null $webhook_api_version = null,
        ?string $webhook_failover_url = null,
        ?string $webhook_url = null,
    ): self {
        $obj = new self;

        $obj->name = $name;
        $obj->whitelisted_destinations = $whitelisted_destinations;

        null !== $alpha_sender && $obj->alpha_sender = $alpha_sender;
        null !== $daily_spend_limit && $obj->daily_spend_limit = $daily_spend_limit;
        null !== $daily_spend_limit_enabled && $obj->daily_spend_limit_enabled = $daily_spend_limit_enabled;
        null !== $enabled && $obj->enabled = $enabled;
        null !== $mms_fall_back_to_sms && $obj->mms_fall_back_to_sms = $mms_fall_back_to_sms;
        null !== $mms_transcoding && $obj->mms_transcoding = $mms_transcoding;
        null !== $mobile_only && $obj->mobile_only = $mobile_only;
        null !== $number_pool_settings && $obj->number_pool_settings = $number_pool_settings;
        null !== $url_shortener_settings && $obj->url_shortener_settings = $url_shortener_settings;
        null !== $webhook_api_version && $obj['webhook_api_version'] = $webhook_api_version;
        null !== $webhook_failover_url && $obj->webhook_failover_url = $webhook_failover_url;
        null !== $webhook_url && $obj->webhook_url = $webhook_url;

        return $obj;
    }

    /**
     * A user friendly name for the messaging profile.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj->name = $name;

        return $obj;
    }

    /**
     * Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]` all destinations will be allowed.
     *
     * @param list<string> $whitelistedDestinations
     */
    public function withWhitelistedDestinations(
        array $whitelistedDestinations
    ): self {
        $obj = clone $this;
        $obj->whitelisted_destinations = $whitelistedDestinations;

        return $obj;
    }

    /**
     * The alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID.
     */
    public function withAlphaSender(?string $alphaSender): self
    {
        $obj = clone $this;
        $obj->alpha_sender = $alphaSender;

        return $obj;
    }

    /**
     * The maximum amount of money (in USD) that can be spent by this profile before midnight UTC.
     */
    public function withDailySpendLimit(string $dailySpendLimit): self
    {
        $obj = clone $this;
        $obj->daily_spend_limit = $dailySpendLimit;

        return $obj;
    }

    /**
     * Whether to enforce the value configured by `daily_spend_limit`.
     */
    public function withDailySpendLimitEnabled(
        bool $dailySpendLimitEnabled
    ): self {
        $obj = clone $this;
        $obj->daily_spend_limit_enabled = $dailySpendLimitEnabled;

        return $obj;
    }

    /**
     * Specifies whether the messaging profile is enabled or not.
     */
    public function withEnabled(bool $enabled): self
    {
        $obj = clone $this;
        $obj->enabled = $enabled;

        return $obj;
    }

    /**
     * enables SMS fallback for MMS messages.
     */
    public function withMmsFallBackToSMS(bool $mmsFallBackToSMS): self
    {
        $obj = clone $this;
        $obj->mms_fall_back_to_sms = $mmsFallBackToSMS;

        return $obj;
    }

    /**
     * enables automated resizing of MMS media.
     */
    public function withMmsTranscoding(bool $mmsTranscoding): self
    {
        $obj = clone $this;
        $obj->mms_transcoding = $mmsTranscoding;

        return $obj;
    }

    /**
     * Send messages only to mobile phone numbers.
     */
    public function withMobileOnly(bool $mobileOnly): self
    {
        $obj = clone $this;
        $obj->mobile_only = $mobileOnly;

        return $obj;
    }

    /**
     * Number Pool allows you to send messages from a pool of numbers of different types, assigning
     * weights to each type. The pool consists of all the long code and toll free numbers
     * assigned to the messaging profile.
     *
     * To disable this feature, set the object field to `null`.
     */
    public function withNumberPoolSettings(
        ?NumberPoolSettings $numberPoolSettings
    ): self {
        $obj = clone $this;
        $obj->number_pool_settings = $numberPoolSettings;

        return $obj;
    }

    /**
     * The URL shortener feature allows automatic replacement of URLs that were generated using
     * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
     * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
     * with links generated by Telnyx. The use of custom links can improve branding and message
     * deliverability.
     *
     * To disable this feature, set the object field to `null`.
     */
    public function withURLShortenerSettings(
        ?URLShortenerSettings $urlShortenerSettings
    ): self {
        $obj = clone $this;
        $obj->url_shortener_settings = $urlShortenerSettings;

        return $obj;
    }

    /**
     * Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
     *
     * @param WebhookAPIVersion|value-of<WebhookAPIVersion> $webhookAPIVersion
     */
    public function withWebhookAPIVersion(
        WebhookAPIVersion|string $webhookAPIVersion
    ): self {
        $obj = clone $this;
        $obj['webhook_api_version'] = $webhookAPIVersion;

        return $obj;
    }

    /**
     * The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
     */
    public function withWebhookFailoverURL(?string $webhookFailoverURL): self
    {
        $obj = clone $this;
        $obj->webhook_failover_url = $webhookFailoverURL;

        return $obj;
    }

    /**
     * The URL where webhooks related to this messaging profile will be sent.
     */
    public function withWebhookURL(?string $webhookURL): self
    {
        $obj = clone $this;
        $obj->webhook_url = $webhookURL;

        return $obj;
    }
}
