<?php

declare(strict_types=1);

namespace Telnyx\MessagingProfiles;

use Telnyx\Core\Attributes\Optional;
use Telnyx\Core\Attributes\Required;
use Telnyx\Core\Concerns\SdkModel;
use Telnyx\Core\Contracts\BaseModel;

/**
 * The URL shortener feature allows automatic replacement of URLs that were generated using
 * a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,
 * is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with
 * with links generated by Telnyx. The use of custom links can improve branding and message
 * deliverability.
 *
 * To disable this feature, set the object field to `null`.
 *
 * @phpstan-type URLShortenerSettingsShape = array{
 *   domain: string,
 *   prefix?: string|null,
 *   replaceBlacklistOnly?: bool|null,
 *   sendWebhooks?: bool|null,
 * }
 */
final class URLShortenerSettings implements BaseModel
{
    /** @use SdkModel<URLShortenerSettingsShape> */
    use SdkModel;

    /**
     * One of the domains provided by the Telnyx URL shortener service.
     */
    #[Required]
    public string $domain;

    /**
     * Optional prefix that can be used to identify your brand, and will appear in the Telnyx generated URLs after the domain name.
     */
    #[Optional]
    public ?string $prefix;

    /**
     * Use the link replacement tool only for links that are specifically blacklisted by Telnyx.
     */
    #[Optional('replace_blacklist_only')]
    public ?bool $replaceBlacklistOnly;

    /**
     * Receive webhooks for when your replaced links are clicked. Webhooks are sent to the webhooks on the messaging profile.
     */
    #[Optional('send_webhooks')]
    public ?bool $sendWebhooks;

    /**
     * `new URLShortenerSettings()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * URLShortenerSettings::with(domain: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new URLShortenerSettings)->withDomain(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $domain,
        ?string $prefix = null,
        ?bool $replaceBlacklistOnly = null,
        ?bool $sendWebhooks = null,
    ): self {
        $self = new self;

        $self['domain'] = $domain;

        null !== $prefix && $self['prefix'] = $prefix;
        null !== $replaceBlacklistOnly && $self['replaceBlacklistOnly'] = $replaceBlacklistOnly;
        null !== $sendWebhooks && $self['sendWebhooks'] = $sendWebhooks;

        return $self;
    }

    /**
     * One of the domains provided by the Telnyx URL shortener service.
     */
    public function withDomain(string $domain): self
    {
        $self = clone $this;
        $self['domain'] = $domain;

        return $self;
    }

    /**
     * Optional prefix that can be used to identify your brand, and will appear in the Telnyx generated URLs after the domain name.
     */
    public function withPrefix(string $prefix): self
    {
        $self = clone $this;
        $self['prefix'] = $prefix;

        return $self;
    }

    /**
     * Use the link replacement tool only for links that are specifically blacklisted by Telnyx.
     */
    public function withReplaceBlacklistOnly(bool $replaceBlacklistOnly): self
    {
        $self = clone $this;
        $self['replaceBlacklistOnly'] = $replaceBlacklistOnly;

        return $self;
    }

    /**
     * Receive webhooks for when your replaced links are clicked. Webhooks are sent to the webhooks on the messaging profile.
     */
    public function withSendWebhooks(bool $sendWebhooks): self
    {
        $self = clone $this;
        $self['sendWebhooks'] = $sendWebhooks;

        return $self;
    }
}
